// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo.proto

package org.example.core.processor.bytedance.proto;

public final class CodeGraphRepo {
  private CodeGraphRepo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_Repo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_Repo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_GlobalNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_GlobalNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_GlobalReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_GlobalReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_Package_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_Package_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_Function_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_Function_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_Function_Variable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_Function_Variable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_FuncSignature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_FuncSignature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrepo.proto\022\036security.sast.codegraph.re" +
      "popb\032\ntype.proto\032\nstmt.proto\"\310\001\n\004Repo\022\n\n" +
      "\002id\030\001 \001(\t\022=\n\007structs\030\002 \003(\0132,.security.sa" +
      "st.codegraph.repopb.StructSchema\0229\n\010pack" +
      "ages\030\004 \003(\0132\'.security.sast.codegraph.rep" +
      "opb.Package\022:\n\010language\030\005 \001(\0162(.security" +
      ".sast.codegraph.repopb.Language\"0\n\004Node\022" +
      "\014\n\004type\030\003 \001(\t\022\014\n\004repr\030\004 \001(\t\022\014\n\004name\030\r \001(" +
      "\t\"S\n\nGlobalNode\022\021\n\tglobal_id\030\001 \001(\t\0222\n\004no" +
      "de\030\002 \001(\0132$.security.sast.codegraph.repop" +
      "b.Node\"$\n\017GlobalReference\022\021\n\tglobal_id\030\001" +
      " \001(\t\"\245\001\n\007Package\022\n\n\002id\030\001 \001(\t\022;\n\tfunction" +
      "s\030\002 \003(\0132(.security.sast.codegraph.repopb" +
      ".Function\022;\n\007globals\030\003 \003(\0132*.security.sa" +
      "st.codegraph.repopb.GlobalNode\022\024\n\014init_f" +
      "unc_id\030\004 \001(\t\"\323\003\n\010Function\022\n\n\002id\030\001 \001(\t\022D\n" +
      "\tvariables\030\002 \003(\01321.security.sast.codegra" +
      "ph.repopb.Function.Variable\022=\n\nstatement" +
      "s\030\003 \003(\0132).security.sast.codegraph.repopb" +
      ".Statement\022\017\n\007arg_ids\030\004 \003(\005\022\024\n\014free_var_" +
      "ids\030\005 \003(\005\022\017\n\007ret_ids\030\006 \003(\005\022\014\n\004name\030\010 \001(\t" +
      "\022@\n\tsignature\030\n \001(\0132-.security.sast.code" +
      "graph.repopb.FuncSignature\022\021\n\tis_ignore\030" +
      "e \001(\010\032\232\001\n\010Variable\022:\n\nlocal_node\030\001 \001(\0132$" +
      ".security.sast.codegraph.repopb.NodeH\000\022E" +
      "\n\nglobal_ref\030\002 \001(\0132/.security.sast.codeg" +
      "raph.repopb.GlobalReferenceH\000B\013\n\treferen" +
      "ce\"I\n\rFuncSignature\022\022\n\nclass_type\030\001 \001(\t\022" +
      "\021\n\targ_types\030\002 \003(\t\022\021\n\tret_types\030\003 \003(\t* \n" +
      "\010Language\022\n\n\006GOLANG\020\000\022\010\n\004JAVA\020\001BE\n*org.e" +
      "xample.core.processor.bytedance.protoB\rC" +
      "odeGraphRepoP\001Z\006repopbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.example.core.processor.bytedance.proto.CodeGraphType.getDescriptor(),
          org.example.core.processor.bytedance.proto.CodeGraphStatement.getDescriptor(),
        });
    internal_static_security_sast_codegraph_repopb_Repo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_security_sast_codegraph_repopb_Repo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_Repo_descriptor,
        new java.lang.String[] { "Id", "Structs", "Packages", "Language", });
    internal_static_security_sast_codegraph_repopb_Node_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_security_sast_codegraph_repopb_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_Node_descriptor,
        new java.lang.String[] { "Type", "Repr", "Name", });
    internal_static_security_sast_codegraph_repopb_GlobalNode_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_security_sast_codegraph_repopb_GlobalNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_GlobalNode_descriptor,
        new java.lang.String[] { "GlobalId", "Node", });
    internal_static_security_sast_codegraph_repopb_GlobalReference_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_security_sast_codegraph_repopb_GlobalReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_GlobalReference_descriptor,
        new java.lang.String[] { "GlobalId", });
    internal_static_security_sast_codegraph_repopb_Package_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_security_sast_codegraph_repopb_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_Package_descriptor,
        new java.lang.String[] { "Id", "Functions", "Globals", "InitFuncId", });
    internal_static_security_sast_codegraph_repopb_Function_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_security_sast_codegraph_repopb_Function_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_Function_descriptor,
        new java.lang.String[] { "Id", "Variables", "Statements", "ArgIds", "FreeVarIds", "RetIds", "Name", "Signature", "IsIgnore", });
    internal_static_security_sast_codegraph_repopb_Function_Variable_descriptor =
      internal_static_security_sast_codegraph_repopb_Function_descriptor.getNestedTypes().get(0);
    internal_static_security_sast_codegraph_repopb_Function_Variable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_Function_Variable_descriptor,
        new java.lang.String[] { "LocalNode", "GlobalRef", "Reference", });
    internal_static_security_sast_codegraph_repopb_FuncSignature_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_security_sast_codegraph_repopb_FuncSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_FuncSignature_descriptor,
        new java.lang.String[] { "ClassType", "ArgTypes", "RetTypes", });
    org.example.core.processor.bytedance.proto.CodeGraphType.getDescriptor();
    org.example.core.processor.bytedance.proto.CodeGraphStatement.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
