// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.processor.bytedance.proto;

public interface CommonFlowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.CommonFlow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 target_id = 1;</code>
   * @return The targetId.
   */
  int getTargetId();

  /**
   * <code>repeated int32 source_ids = 2;</code>
   * @return A list containing the sourceIds.
   */
  java.util.List<java.lang.Integer> getSourceIdsList();
  /**
   * <code>repeated int32 source_ids = 2;</code>
   * @return The count of sourceIds.
   */
  int getSourceIdsCount();
  /**
   * <code>repeated int32 source_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The sourceIds at the given index.
   */
  int getSourceIds(int index);
}
