// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo.proto

package org.example.core.processor.bytedance.proto;

public interface GlobalNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.GlobalNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string global_id = 1;</code>
   * @return The globalId.
   */
  java.lang.String getGlobalId();
  /**
   * <code>string global_id = 1;</code>
   * @return The bytes for globalId.
   */
  com.google.protobuf.ByteString
      getGlobalIdBytes();

  /**
   * <code>.security.sast.codegraph.repopb.Node node = 2;</code>
   * @return Whether the node field is set.
   */
  boolean hasNode();
  /**
   * <code>.security.sast.codegraph.repopb.Node node = 2;</code>
   * @return The node.
   */
  org.example.core.processor.bytedance.proto.Node getNode();
  /**
   * <code>.security.sast.codegraph.repopb.Node node = 2;</code>
   */
  org.example.core.processor.bytedance.proto.NodeOrBuilder getNodeOrBuilder();
}
