// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.processor.bytedance.proto;

/**
 * <pre>
 * Operation target = operator(operand)
 * </pre>
 *
 * Protobuf type {@code security.sast.codegraph.repopb.Operation}
 */
public final class Operation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.sast.codegraph.repopb.Operation)
    OperationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Operation.newBuilder() to construct.
  private Operation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Operation() {
    operator_ = 0;
    operandIds_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Operation();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.core.processor.bytedance.proto.CodeGraphStatement.internal_static_security_sast_codegraph_repopb_Operation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.core.processor.bytedance.proto.CodeGraphStatement.internal_static_security_sast_codegraph_repopb_Operation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.core.processor.bytedance.proto.Operation.class, org.example.core.processor.bytedance.proto.Operation.Builder.class);
  }

  public static final int TARGET_ID_FIELD_NUMBER = 1;
  private int targetId_ = 0;
  /**
   * <code>int32 target_id = 1;</code>
   * @return The targetId.
   */
  @java.lang.Override
  public int getTargetId() {
    return targetId_;
  }

  public static final int OPERATOR_FIELD_NUMBER = 2;
  private int operator_ = 0;
  /**
   * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
   * @return The enum numeric value on the wire for operator.
   */
  @java.lang.Override public int getOperatorValue() {
    return operator_;
  }
  /**
   * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
   * @return The operator.
   */
  @java.lang.Override public org.example.core.processor.bytedance.proto.Operator getOperator() {
    org.example.core.processor.bytedance.proto.Operator result = org.example.core.processor.bytedance.proto.Operator.forNumber(operator_);
    return result == null ? org.example.core.processor.bytedance.proto.Operator.UNRECOGNIZED : result;
  }

  public static final int OPERAND_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList operandIds_;
  /**
   * <code>repeated int32 operand_ids = 3;</code>
   * @return A list containing the operandIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getOperandIdsList() {
    return operandIds_;
  }
  /**
   * <code>repeated int32 operand_ids = 3;</code>
   * @return The count of operandIds.
   */
  public int getOperandIdsCount() {
    return operandIds_.size();
  }
  /**
   * <code>repeated int32 operand_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The operandIds at the given index.
   */
  public int getOperandIds(int index) {
    return operandIds_.getInt(index);
  }
  private int operandIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (targetId_ != 0) {
      output.writeInt32(1, targetId_);
    }
    if (operator_ != org.example.core.processor.bytedance.proto.Operator.ADD.getNumber()) {
      output.writeEnum(2, operator_);
    }
    if (getOperandIdsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(operandIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < operandIds_.size(); i++) {
      output.writeInt32NoTag(operandIds_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (targetId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, targetId_);
    }
    if (operator_ != org.example.core.processor.bytedance.proto.Operator.ADD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, operator_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < operandIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(operandIds_.getInt(i));
      }
      size += dataSize;
      if (!getOperandIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      operandIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.core.processor.bytedance.proto.Operation)) {
      return super.equals(obj);
    }
    org.example.core.processor.bytedance.proto.Operation other = (org.example.core.processor.bytedance.proto.Operation) obj;

    if (getTargetId()
        != other.getTargetId()) return false;
    if (operator_ != other.operator_) return false;
    if (!getOperandIdsList()
        .equals(other.getOperandIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetId();
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + operator_;
    if (getOperandIdsCount() > 0) {
      hash = (37 * hash) + OPERAND_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getOperandIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.core.processor.bytedance.proto.Operation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.core.processor.bytedance.proto.Operation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.core.processor.bytedance.proto.Operation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.core.processor.bytedance.proto.Operation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Operation target = operator(operand)
   * </pre>
   *
   * Protobuf type {@code security.sast.codegraph.repopb.Operation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.sast.codegraph.repopb.Operation)
      org.example.core.processor.bytedance.proto.OperationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.core.processor.bytedance.proto.CodeGraphStatement.internal_static_security_sast_codegraph_repopb_Operation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.core.processor.bytedance.proto.CodeGraphStatement.internal_static_security_sast_codegraph_repopb_Operation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.core.processor.bytedance.proto.Operation.class, org.example.core.processor.bytedance.proto.Operation.Builder.class);
    }

    // Construct using org.example.core.processor.bytedance.proto.Operation.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      targetId_ = 0;
      operator_ = 0;
      operandIds_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.core.processor.bytedance.proto.CodeGraphStatement.internal_static_security_sast_codegraph_repopb_Operation_descriptor;
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Operation getDefaultInstanceForType() {
      return org.example.core.processor.bytedance.proto.Operation.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Operation build() {
      org.example.core.processor.bytedance.proto.Operation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Operation buildPartial() {
      org.example.core.processor.bytedance.proto.Operation result = new org.example.core.processor.bytedance.proto.Operation(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.core.processor.bytedance.proto.Operation result) {
      if (((bitField0_ & 0x00000004) != 0)) {
        operandIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.operandIds_ = operandIds_;
    }

    private void buildPartial0(org.example.core.processor.bytedance.proto.Operation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.targetId_ = targetId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.operator_ = operator_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.core.processor.bytedance.proto.Operation) {
        return mergeFrom((org.example.core.processor.bytedance.proto.Operation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.core.processor.bytedance.proto.Operation other) {
      if (other == org.example.core.processor.bytedance.proto.Operation.getDefaultInstance()) return this;
      if (other.getTargetId() != 0) {
        setTargetId(other.getTargetId());
      }
      if (other.operator_ != 0) {
        setOperatorValue(other.getOperatorValue());
      }
      if (!other.operandIds_.isEmpty()) {
        if (operandIds_.isEmpty()) {
          operandIds_ = other.operandIds_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureOperandIdsIsMutable();
          operandIds_.addAll(other.operandIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              targetId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              operator_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              int v = input.readInt32();
              ensureOperandIdsIsMutable();
              operandIds_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureOperandIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                operandIds_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int targetId_ ;
    /**
     * <code>int32 target_id = 1;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public int getTargetId() {
      return targetId_;
    }
    /**
     * <code>int32 target_id = 1;</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(int value) {

      targetId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 target_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      targetId_ = 0;
      onChanged();
      return this;
    }

    private int operator_ = 0;
    /**
     * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
     * @return The enum numeric value on the wire for operator.
     */
    @java.lang.Override public int getOperatorValue() {
      return operator_;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
     * @param value The enum numeric value on the wire for operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorValue(int value) {
      operator_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
     * @return The operator.
     */
    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Operator getOperator() {
      org.example.core.processor.bytedance.proto.Operator result = org.example.core.processor.bytedance.proto.Operator.forNumber(operator_);
      return result == null ? org.example.core.processor.bytedance.proto.Operator.UNRECOGNIZED : result;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
     * @param value The operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperator(org.example.core.processor.bytedance.proto.Operator value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      operator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperator() {
      bitField0_ = (bitField0_ & ~0x00000002);
      operator_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList operandIds_ = emptyIntList();
    private void ensureOperandIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        operandIds_ = mutableCopy(operandIds_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @return A list containing the operandIds.
     */
    public java.util.List<java.lang.Integer>
        getOperandIdsList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(operandIds_) : operandIds_;
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @return The count of operandIds.
     */
    public int getOperandIdsCount() {
      return operandIds_.size();
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The operandIds at the given index.
     */
    public int getOperandIds(int index) {
      return operandIds_.getInt(index);
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The operandIds to set.
     * @return This builder for chaining.
     */
    public Builder setOperandIds(
        int index, int value) {

      ensureOperandIdsIsMutable();
      operandIds_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @param value The operandIds to add.
     * @return This builder for chaining.
     */
    public Builder addOperandIds(int value) {

      ensureOperandIdsIsMutable();
      operandIds_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @param values The operandIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllOperandIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureOperandIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, operandIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 operand_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperandIds() {
      operandIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.sast.codegraph.repopb.Operation)
  }

  // @@protoc_insertion_point(class_scope:security.sast.codegraph.repopb.Operation)
  private static final org.example.core.processor.bytedance.proto.Operation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.core.processor.bytedance.proto.Operation();
  }

  public static org.example.core.processor.bytedance.proto.Operation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Operation>
      PARSER = new com.google.protobuf.AbstractParser<Operation>() {
    @java.lang.Override
    public Operation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Operation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Operation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.core.processor.bytedance.proto.Operation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

