// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.processor.bytedance.proto;

public interface OperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.Operation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 target_id = 1;</code>
   * @return The targetId.
   */
  int getTargetId();

  /**
   * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
   * @return The enum numeric value on the wire for operator.
   */
  int getOperatorValue();
  /**
   * <code>.security.sast.codegraph.repopb.Operator operator = 2;</code>
   * @return The operator.
   */
  org.example.core.processor.bytedance.proto.Operator getOperator();

  /**
   * <code>repeated int32 operand_ids = 3;</code>
   * @return A list containing the operandIds.
   */
  java.util.List<java.lang.Integer> getOperandIdsList();
  /**
   * <code>repeated int32 operand_ids = 3;</code>
   * @return The count of operandIds.
   */
  int getOperandIdsCount();
  /**
   * <code>repeated int32 operand_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The operandIds at the given index.
   */
  int getOperandIds(int index);
}
