// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo.proto

package org.example.core.processor.bytedance.proto;

/**
 * Protobuf type {@code security.sast.codegraph.repopb.Package}
 */
public final class Package extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.sast.codegraph.repopb.Package)
    PackageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Package.newBuilder() to construct.
  private Package(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Package() {
    id_ = "";
    functions_ = java.util.Collections.emptyList();
    globals_ = java.util.Collections.emptyList();
    initFuncId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Package();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Package_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Package_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.core.processor.bytedance.proto.Package.class, org.example.core.processor.bytedance.proto.Package.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.example.core.processor.bytedance.proto.Function> functions_;
  /**
   * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.core.processor.bytedance.proto.Function> getFunctionsList() {
    return functions_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.core.processor.bytedance.proto.FunctionOrBuilder> 
      getFunctionsOrBuilderList() {
    return functions_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
   */
  @java.lang.Override
  public int getFunctionsCount() {
    return functions_.size();
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.Function getFunctions(int index) {
    return functions_.get(index);
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.FunctionOrBuilder getFunctionsOrBuilder(
      int index) {
    return functions_.get(index);
  }

  public static final int GLOBALS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<org.example.core.processor.bytedance.proto.GlobalNode> globals_;
  /**
   * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.core.processor.bytedance.proto.GlobalNode> getGlobalsList() {
    return globals_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder> 
      getGlobalsOrBuilderList() {
    return globals_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
   */
  @java.lang.Override
  public int getGlobalsCount() {
    return globals_.size();
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.GlobalNode getGlobals(int index) {
    return globals_.get(index);
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder getGlobalsOrBuilder(
      int index) {
    return globals_.get(index);
  }

  public static final int INIT_FUNC_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object initFuncId_ = "";
  /**
   * <pre>
   * init_func will be called before calling functions in the package
   * </pre>
   *
   * <code>string init_func_id = 4;</code>
   * @return The initFuncId.
   */
  @java.lang.Override
  public java.lang.String getInitFuncId() {
    java.lang.Object ref = initFuncId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      initFuncId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * init_func will be called before calling functions in the package
   * </pre>
   *
   * <code>string init_func_id = 4;</code>
   * @return The bytes for initFuncId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInitFuncIdBytes() {
    java.lang.Object ref = initFuncId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      initFuncId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < functions_.size(); i++) {
      output.writeMessage(2, functions_.get(i));
    }
    for (int i = 0; i < globals_.size(); i++) {
      output.writeMessage(3, globals_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initFuncId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, initFuncId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < functions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, functions_.get(i));
    }
    for (int i = 0; i < globals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, globals_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initFuncId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, initFuncId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.core.processor.bytedance.proto.Package)) {
      return super.equals(obj);
    }
    org.example.core.processor.bytedance.proto.Package other = (org.example.core.processor.bytedance.proto.Package) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getFunctionsList()
        .equals(other.getFunctionsList())) return false;
    if (!getGlobalsList()
        .equals(other.getGlobalsList())) return false;
    if (!getInitFuncId()
        .equals(other.getInitFuncId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getFunctionsCount() > 0) {
      hash = (37 * hash) + FUNCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionsList().hashCode();
    }
    if (getGlobalsCount() > 0) {
      hash = (37 * hash) + GLOBALS_FIELD_NUMBER;
      hash = (53 * hash) + getGlobalsList().hashCode();
    }
    hash = (37 * hash) + INIT_FUNC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInitFuncId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.core.processor.bytedance.proto.Package parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.core.processor.bytedance.proto.Package parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.core.processor.bytedance.proto.Package parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.core.processor.bytedance.proto.Package prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code security.sast.codegraph.repopb.Package}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.sast.codegraph.repopb.Package)
      org.example.core.processor.bytedance.proto.PackageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Package_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.core.processor.bytedance.proto.Package.class, org.example.core.processor.bytedance.proto.Package.Builder.class);
    }

    // Construct using org.example.core.processor.bytedance.proto.Package.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      if (functionsBuilder_ == null) {
        functions_ = java.util.Collections.emptyList();
      } else {
        functions_ = null;
        functionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (globalsBuilder_ == null) {
        globals_ = java.util.Collections.emptyList();
      } else {
        globals_ = null;
        globalsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      initFuncId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Package_descriptor;
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Package getDefaultInstanceForType() {
      return org.example.core.processor.bytedance.proto.Package.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Package build() {
      org.example.core.processor.bytedance.proto.Package result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Package buildPartial() {
      org.example.core.processor.bytedance.proto.Package result = new org.example.core.processor.bytedance.proto.Package(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.core.processor.bytedance.proto.Package result) {
      if (functionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          functions_ = java.util.Collections.unmodifiableList(functions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.functions_ = functions_;
      } else {
        result.functions_ = functionsBuilder_.build();
      }
      if (globalsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          globals_ = java.util.Collections.unmodifiableList(globals_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.globals_ = globals_;
      } else {
        result.globals_ = globalsBuilder_.build();
      }
    }

    private void buildPartial0(org.example.core.processor.bytedance.proto.Package result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.initFuncId_ = initFuncId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.core.processor.bytedance.proto.Package) {
        return mergeFrom((org.example.core.processor.bytedance.proto.Package)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.core.processor.bytedance.proto.Package other) {
      if (other == org.example.core.processor.bytedance.proto.Package.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (functionsBuilder_ == null) {
        if (!other.functions_.isEmpty()) {
          if (functions_.isEmpty()) {
            functions_ = other.functions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFunctionsIsMutable();
            functions_.addAll(other.functions_);
          }
          onChanged();
        }
      } else {
        if (!other.functions_.isEmpty()) {
          if (functionsBuilder_.isEmpty()) {
            functionsBuilder_.dispose();
            functionsBuilder_ = null;
            functions_ = other.functions_;
            bitField0_ = (bitField0_ & ~0x00000002);
            functionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFunctionsFieldBuilder() : null;
          } else {
            functionsBuilder_.addAllMessages(other.functions_);
          }
        }
      }
      if (globalsBuilder_ == null) {
        if (!other.globals_.isEmpty()) {
          if (globals_.isEmpty()) {
            globals_ = other.globals_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureGlobalsIsMutable();
            globals_.addAll(other.globals_);
          }
          onChanged();
        }
      } else {
        if (!other.globals_.isEmpty()) {
          if (globalsBuilder_.isEmpty()) {
            globalsBuilder_.dispose();
            globalsBuilder_ = null;
            globals_ = other.globals_;
            bitField0_ = (bitField0_ & ~0x00000004);
            globalsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGlobalsFieldBuilder() : null;
          } else {
            globalsBuilder_.addAllMessages(other.globals_);
          }
        }
      }
      if (!other.getInitFuncId().isEmpty()) {
        initFuncId_ = other.initFuncId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              org.example.core.processor.bytedance.proto.Function m =
                  input.readMessage(
                      org.example.core.processor.bytedance.proto.Function.parser(),
                      extensionRegistry);
              if (functionsBuilder_ == null) {
                ensureFunctionsIsMutable();
                functions_.add(m);
              } else {
                functionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              org.example.core.processor.bytedance.proto.GlobalNode m =
                  input.readMessage(
                      org.example.core.processor.bytedance.proto.GlobalNode.parser(),
                      extensionRegistry);
              if (globalsBuilder_ == null) {
                ensureGlobalsIsMutable();
                globals_.add(m);
              } else {
                globalsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              initFuncId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<org.example.core.processor.bytedance.proto.Function> functions_ =
      java.util.Collections.emptyList();
    private void ensureFunctionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        functions_ = new java.util.ArrayList<org.example.core.processor.bytedance.proto.Function>(functions_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.Function, org.example.core.processor.bytedance.proto.Function.Builder, org.example.core.processor.bytedance.proto.FunctionOrBuilder> functionsBuilder_;

    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.Function> getFunctionsList() {
      if (functionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(functions_);
      } else {
        return functionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public int getFunctionsCount() {
      if (functionsBuilder_ == null) {
        return functions_.size();
      } else {
        return functionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.Function getFunctions(int index) {
      if (functionsBuilder_ == null) {
        return functions_.get(index);
      } else {
        return functionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder setFunctions(
        int index, org.example.core.processor.bytedance.proto.Function value) {
      if (functionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionsIsMutable();
        functions_.set(index, value);
        onChanged();
      } else {
        functionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder setFunctions(
        int index, org.example.core.processor.bytedance.proto.Function.Builder builderForValue) {
      if (functionsBuilder_ == null) {
        ensureFunctionsIsMutable();
        functions_.set(index, builderForValue.build());
        onChanged();
      } else {
        functionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder addFunctions(org.example.core.processor.bytedance.proto.Function value) {
      if (functionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionsIsMutable();
        functions_.add(value);
        onChanged();
      } else {
        functionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder addFunctions(
        int index, org.example.core.processor.bytedance.proto.Function value) {
      if (functionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionsIsMutable();
        functions_.add(index, value);
        onChanged();
      } else {
        functionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder addFunctions(
        org.example.core.processor.bytedance.proto.Function.Builder builderForValue) {
      if (functionsBuilder_ == null) {
        ensureFunctionsIsMutable();
        functions_.add(builderForValue.build());
        onChanged();
      } else {
        functionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder addFunctions(
        int index, org.example.core.processor.bytedance.proto.Function.Builder builderForValue) {
      if (functionsBuilder_ == null) {
        ensureFunctionsIsMutable();
        functions_.add(index, builderForValue.build());
        onChanged();
      } else {
        functionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder addAllFunctions(
        java.lang.Iterable<? extends org.example.core.processor.bytedance.proto.Function> values) {
      if (functionsBuilder_ == null) {
        ensureFunctionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, functions_);
        onChanged();
      } else {
        functionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder clearFunctions() {
      if (functionsBuilder_ == null) {
        functions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        functionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public Builder removeFunctions(int index) {
      if (functionsBuilder_ == null) {
        ensureFunctionsIsMutable();
        functions_.remove(index);
        onChanged();
      } else {
        functionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.Function.Builder getFunctionsBuilder(
        int index) {
      return getFunctionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.FunctionOrBuilder getFunctionsOrBuilder(
        int index) {
      if (functionsBuilder_ == null) {
        return functions_.get(index);  } else {
        return functionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public java.util.List<? extends org.example.core.processor.bytedance.proto.FunctionOrBuilder> 
         getFunctionsOrBuilderList() {
      if (functionsBuilder_ != null) {
        return functionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(functions_);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.Function.Builder addFunctionsBuilder() {
      return getFunctionsFieldBuilder().addBuilder(
          org.example.core.processor.bytedance.proto.Function.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.Function.Builder addFunctionsBuilder(
        int index) {
      return getFunctionsFieldBuilder().addBuilder(
          index, org.example.core.processor.bytedance.proto.Function.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Function functions = 2;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.Function.Builder> 
         getFunctionsBuilderList() {
      return getFunctionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.Function, org.example.core.processor.bytedance.proto.Function.Builder, org.example.core.processor.bytedance.proto.FunctionOrBuilder> 
        getFunctionsFieldBuilder() {
      if (functionsBuilder_ == null) {
        functionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.core.processor.bytedance.proto.Function, org.example.core.processor.bytedance.proto.Function.Builder, org.example.core.processor.bytedance.proto.FunctionOrBuilder>(
                functions_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        functions_ = null;
      }
      return functionsBuilder_;
    }

    private java.util.List<org.example.core.processor.bytedance.proto.GlobalNode> globals_ =
      java.util.Collections.emptyList();
    private void ensureGlobalsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        globals_ = new java.util.ArrayList<org.example.core.processor.bytedance.proto.GlobalNode>(globals_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.GlobalNode, org.example.core.processor.bytedance.proto.GlobalNode.Builder, org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder> globalsBuilder_;

    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.GlobalNode> getGlobalsList() {
      if (globalsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(globals_);
      } else {
        return globalsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public int getGlobalsCount() {
      if (globalsBuilder_ == null) {
        return globals_.size();
      } else {
        return globalsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public org.example.core.processor.bytedance.proto.GlobalNode getGlobals(int index) {
      if (globalsBuilder_ == null) {
        return globals_.get(index);
      } else {
        return globalsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder setGlobals(
        int index, org.example.core.processor.bytedance.proto.GlobalNode value) {
      if (globalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalsIsMutable();
        globals_.set(index, value);
        onChanged();
      } else {
        globalsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder setGlobals(
        int index, org.example.core.processor.bytedance.proto.GlobalNode.Builder builderForValue) {
      if (globalsBuilder_ == null) {
        ensureGlobalsIsMutable();
        globals_.set(index, builderForValue.build());
        onChanged();
      } else {
        globalsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder addGlobals(org.example.core.processor.bytedance.proto.GlobalNode value) {
      if (globalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalsIsMutable();
        globals_.add(value);
        onChanged();
      } else {
        globalsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder addGlobals(
        int index, org.example.core.processor.bytedance.proto.GlobalNode value) {
      if (globalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalsIsMutable();
        globals_.add(index, value);
        onChanged();
      } else {
        globalsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder addGlobals(
        org.example.core.processor.bytedance.proto.GlobalNode.Builder builderForValue) {
      if (globalsBuilder_ == null) {
        ensureGlobalsIsMutable();
        globals_.add(builderForValue.build());
        onChanged();
      } else {
        globalsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder addGlobals(
        int index, org.example.core.processor.bytedance.proto.GlobalNode.Builder builderForValue) {
      if (globalsBuilder_ == null) {
        ensureGlobalsIsMutable();
        globals_.add(index, builderForValue.build());
        onChanged();
      } else {
        globalsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder addAllGlobals(
        java.lang.Iterable<? extends org.example.core.processor.bytedance.proto.GlobalNode> values) {
      if (globalsBuilder_ == null) {
        ensureGlobalsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, globals_);
        onChanged();
      } else {
        globalsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder clearGlobals() {
      if (globalsBuilder_ == null) {
        globals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        globalsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public Builder removeGlobals(int index) {
      if (globalsBuilder_ == null) {
        ensureGlobalsIsMutable();
        globals_.remove(index);
        onChanged();
      } else {
        globalsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public org.example.core.processor.bytedance.proto.GlobalNode.Builder getGlobalsBuilder(
        int index) {
      return getGlobalsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder getGlobalsOrBuilder(
        int index) {
      if (globalsBuilder_ == null) {
        return globals_.get(index);  } else {
        return globalsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public java.util.List<? extends org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder> 
         getGlobalsOrBuilderList() {
      if (globalsBuilder_ != null) {
        return globalsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(globals_);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public org.example.core.processor.bytedance.proto.GlobalNode.Builder addGlobalsBuilder() {
      return getGlobalsFieldBuilder().addBuilder(
          org.example.core.processor.bytedance.proto.GlobalNode.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public org.example.core.processor.bytedance.proto.GlobalNode.Builder addGlobalsBuilder(
        int index) {
      return getGlobalsFieldBuilder().addBuilder(
          index, org.example.core.processor.bytedance.proto.GlobalNode.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.GlobalNode globals = 3;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.GlobalNode.Builder> 
         getGlobalsBuilderList() {
      return getGlobalsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.GlobalNode, org.example.core.processor.bytedance.proto.GlobalNode.Builder, org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder> 
        getGlobalsFieldBuilder() {
      if (globalsBuilder_ == null) {
        globalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.core.processor.bytedance.proto.GlobalNode, org.example.core.processor.bytedance.proto.GlobalNode.Builder, org.example.core.processor.bytedance.proto.GlobalNodeOrBuilder>(
                globals_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        globals_ = null;
      }
      return globalsBuilder_;
    }

    private java.lang.Object initFuncId_ = "";
    /**
     * <pre>
     * init_func will be called before calling functions in the package
     * </pre>
     *
     * <code>string init_func_id = 4;</code>
     * @return The initFuncId.
     */
    public java.lang.String getInitFuncId() {
      java.lang.Object ref = initFuncId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initFuncId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * init_func will be called before calling functions in the package
     * </pre>
     *
     * <code>string init_func_id = 4;</code>
     * @return The bytes for initFuncId.
     */
    public com.google.protobuf.ByteString
        getInitFuncIdBytes() {
      java.lang.Object ref = initFuncId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initFuncId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * init_func will be called before calling functions in the package
     * </pre>
     *
     * <code>string init_func_id = 4;</code>
     * @param value The initFuncId to set.
     * @return This builder for chaining.
     */
    public Builder setInitFuncId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      initFuncId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * init_func will be called before calling functions in the package
     * </pre>
     *
     * <code>string init_func_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitFuncId() {
      initFuncId_ = getDefaultInstance().getInitFuncId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * init_func will be called before calling functions in the package
     * </pre>
     *
     * <code>string init_func_id = 4;</code>
     * @param value The bytes for initFuncId to set.
     * @return This builder for chaining.
     */
    public Builder setInitFuncIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      initFuncId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.sast.codegraph.repopb.Package)
  }

  // @@protoc_insertion_point(class_scope:security.sast.codegraph.repopb.Package)
  private static final org.example.core.processor.bytedance.proto.Package DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.core.processor.bytedance.proto.Package();
  }

  public static org.example.core.processor.bytedance.proto.Package getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Package>
      PARSER = new com.google.protobuf.AbstractParser<Package>() {
    @java.lang.Override
    public Package parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Package> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Package> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.core.processor.bytedance.proto.Package getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

