// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo.proto

package org.example.core.processor.bytedance.proto;

/**
 * Protobuf type {@code security.sast.codegraph.repopb.Repo}
 */
public final class Repo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.sast.codegraph.repopb.Repo)
    RepoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Repo.newBuilder() to construct.
  private Repo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Repo() {
    id_ = "";
    structs_ = java.util.Collections.emptyList();
    packages_ = java.util.Collections.emptyList();
    language_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Repo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Repo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Repo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.core.processor.bytedance.proto.Repo.class, org.example.core.processor.bytedance.proto.Repo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * repo_name
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * repo_name
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRUCTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.example.core.processor.bytedance.proto.StructSchema> structs_;
  /**
   * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.core.processor.bytedance.proto.StructSchema> getStructsList() {
    return structs_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.core.processor.bytedance.proto.StructSchemaOrBuilder> 
      getStructsOrBuilderList() {
    return structs_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
   */
  @java.lang.Override
  public int getStructsCount() {
    return structs_.size();
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.StructSchema getStructs(int index) {
    return structs_.get(index);
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.StructSchemaOrBuilder getStructsOrBuilder(
      int index) {
    return structs_.get(index);
  }

  public static final int PACKAGES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<org.example.core.processor.bytedance.proto.Package> packages_;
  /**
   * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.core.processor.bytedance.proto.Package> getPackagesList() {
    return packages_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.core.processor.bytedance.proto.PackageOrBuilder> 
      getPackagesOrBuilderList() {
    return packages_;
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
   */
  @java.lang.Override
  public int getPackagesCount() {
    return packages_.size();
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.Package getPackages(int index) {
    return packages_.get(index);
  }
  /**
   * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
   */
  @java.lang.Override
  public org.example.core.processor.bytedance.proto.PackageOrBuilder getPackagesOrBuilder(
      int index) {
    return packages_.get(index);
  }

  public static final int LANGUAGE_FIELD_NUMBER = 5;
  private int language_ = 0;
  /**
   * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
   * @return The enum numeric value on the wire for language.
   */
  @java.lang.Override public int getLanguageValue() {
    return language_;
  }
  /**
   * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
   * @return The language.
   */
  @java.lang.Override public org.example.core.processor.bytedance.proto.Language getLanguage() {
    org.example.core.processor.bytedance.proto.Language result = org.example.core.processor.bytedance.proto.Language.forNumber(language_);
    return result == null ? org.example.core.processor.bytedance.proto.Language.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < structs_.size(); i++) {
      output.writeMessage(2, structs_.get(i));
    }
    for (int i = 0; i < packages_.size(); i++) {
      output.writeMessage(4, packages_.get(i));
    }
    if (language_ != org.example.core.processor.bytedance.proto.Language.GOLANG.getNumber()) {
      output.writeEnum(5, language_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < structs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, structs_.get(i));
    }
    for (int i = 0; i < packages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, packages_.get(i));
    }
    if (language_ != org.example.core.processor.bytedance.proto.Language.GOLANG.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, language_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.core.processor.bytedance.proto.Repo)) {
      return super.equals(obj);
    }
    org.example.core.processor.bytedance.proto.Repo other = (org.example.core.processor.bytedance.proto.Repo) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getStructsList()
        .equals(other.getStructsList())) return false;
    if (!getPackagesList()
        .equals(other.getPackagesList())) return false;
    if (language_ != other.language_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getStructsCount() > 0) {
      hash = (37 * hash) + STRUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getStructsList().hashCode();
    }
    if (getPackagesCount() > 0) {
      hash = (37 * hash) + PACKAGES_FIELD_NUMBER;
      hash = (53 * hash) + getPackagesList().hashCode();
    }
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + language_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.core.processor.bytedance.proto.Repo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.core.processor.bytedance.proto.Repo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.core.processor.bytedance.proto.Repo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.core.processor.bytedance.proto.Repo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code security.sast.codegraph.repopb.Repo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.sast.codegraph.repopb.Repo)
      org.example.core.processor.bytedance.proto.RepoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Repo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Repo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.core.processor.bytedance.proto.Repo.class, org.example.core.processor.bytedance.proto.Repo.Builder.class);
    }

    // Construct using org.example.core.processor.bytedance.proto.Repo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      if (structsBuilder_ == null) {
        structs_ = java.util.Collections.emptyList();
      } else {
        structs_ = null;
        structsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (packagesBuilder_ == null) {
        packages_ = java.util.Collections.emptyList();
      } else {
        packages_ = null;
        packagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      language_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.core.processor.bytedance.proto.CodeGraphRepo.internal_static_security_sast_codegraph_repopb_Repo_descriptor;
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Repo getDefaultInstanceForType() {
      return org.example.core.processor.bytedance.proto.Repo.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Repo build() {
      org.example.core.processor.bytedance.proto.Repo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Repo buildPartial() {
      org.example.core.processor.bytedance.proto.Repo result = new org.example.core.processor.bytedance.proto.Repo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.core.processor.bytedance.proto.Repo result) {
      if (structsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          structs_ = java.util.Collections.unmodifiableList(structs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.structs_ = structs_;
      } else {
        result.structs_ = structsBuilder_.build();
      }
      if (packagesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          packages_ = java.util.Collections.unmodifiableList(packages_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.packages_ = packages_;
      } else {
        result.packages_ = packagesBuilder_.build();
      }
    }

    private void buildPartial0(org.example.core.processor.bytedance.proto.Repo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.language_ = language_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.core.processor.bytedance.proto.Repo) {
        return mergeFrom((org.example.core.processor.bytedance.proto.Repo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.core.processor.bytedance.proto.Repo other) {
      if (other == org.example.core.processor.bytedance.proto.Repo.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (structsBuilder_ == null) {
        if (!other.structs_.isEmpty()) {
          if (structs_.isEmpty()) {
            structs_ = other.structs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStructsIsMutable();
            structs_.addAll(other.structs_);
          }
          onChanged();
        }
      } else {
        if (!other.structs_.isEmpty()) {
          if (structsBuilder_.isEmpty()) {
            structsBuilder_.dispose();
            structsBuilder_ = null;
            structs_ = other.structs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            structsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStructsFieldBuilder() : null;
          } else {
            structsBuilder_.addAllMessages(other.structs_);
          }
        }
      }
      if (packagesBuilder_ == null) {
        if (!other.packages_.isEmpty()) {
          if (packages_.isEmpty()) {
            packages_ = other.packages_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePackagesIsMutable();
            packages_.addAll(other.packages_);
          }
          onChanged();
        }
      } else {
        if (!other.packages_.isEmpty()) {
          if (packagesBuilder_.isEmpty()) {
            packagesBuilder_.dispose();
            packagesBuilder_ = null;
            packages_ = other.packages_;
            bitField0_ = (bitField0_ & ~0x00000004);
            packagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPackagesFieldBuilder() : null;
          } else {
            packagesBuilder_.addAllMessages(other.packages_);
          }
        }
      }
      if (other.language_ != 0) {
        setLanguageValue(other.getLanguageValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              org.example.core.processor.bytedance.proto.StructSchema m =
                  input.readMessage(
                      org.example.core.processor.bytedance.proto.StructSchema.parser(),
                      extensionRegistry);
              if (structsBuilder_ == null) {
                ensureStructsIsMutable();
                structs_.add(m);
              } else {
                structsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 34: {
              org.example.core.processor.bytedance.proto.Package m =
                  input.readMessage(
                      org.example.core.processor.bytedance.proto.Package.parser(),
                      extensionRegistry);
              if (packagesBuilder_ == null) {
                ensurePackagesIsMutable();
                packages_.add(m);
              } else {
                packagesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              language_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * repo_name
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * repo_name
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * repo_name
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * repo_name
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * repo_name
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<org.example.core.processor.bytedance.proto.StructSchema> structs_ =
      java.util.Collections.emptyList();
    private void ensureStructsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        structs_ = new java.util.ArrayList<org.example.core.processor.bytedance.proto.StructSchema>(structs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.StructSchema, org.example.core.processor.bytedance.proto.StructSchema.Builder, org.example.core.processor.bytedance.proto.StructSchemaOrBuilder> structsBuilder_;

    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.StructSchema> getStructsList() {
      if (structsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(structs_);
      } else {
        return structsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public int getStructsCount() {
      if (structsBuilder_ == null) {
        return structs_.size();
      } else {
        return structsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.StructSchema getStructs(int index) {
      if (structsBuilder_ == null) {
        return structs_.get(index);
      } else {
        return structsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder setStructs(
        int index, org.example.core.processor.bytedance.proto.StructSchema value) {
      if (structsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStructsIsMutable();
        structs_.set(index, value);
        onChanged();
      } else {
        structsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder setStructs(
        int index, org.example.core.processor.bytedance.proto.StructSchema.Builder builderForValue) {
      if (structsBuilder_ == null) {
        ensureStructsIsMutable();
        structs_.set(index, builderForValue.build());
        onChanged();
      } else {
        structsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder addStructs(org.example.core.processor.bytedance.proto.StructSchema value) {
      if (structsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStructsIsMutable();
        structs_.add(value);
        onChanged();
      } else {
        structsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder addStructs(
        int index, org.example.core.processor.bytedance.proto.StructSchema value) {
      if (structsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStructsIsMutable();
        structs_.add(index, value);
        onChanged();
      } else {
        structsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder addStructs(
        org.example.core.processor.bytedance.proto.StructSchema.Builder builderForValue) {
      if (structsBuilder_ == null) {
        ensureStructsIsMutable();
        structs_.add(builderForValue.build());
        onChanged();
      } else {
        structsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder addStructs(
        int index, org.example.core.processor.bytedance.proto.StructSchema.Builder builderForValue) {
      if (structsBuilder_ == null) {
        ensureStructsIsMutable();
        structs_.add(index, builderForValue.build());
        onChanged();
      } else {
        structsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder addAllStructs(
        java.lang.Iterable<? extends org.example.core.processor.bytedance.proto.StructSchema> values) {
      if (structsBuilder_ == null) {
        ensureStructsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, structs_);
        onChanged();
      } else {
        structsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder clearStructs() {
      if (structsBuilder_ == null) {
        structs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        structsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public Builder removeStructs(int index) {
      if (structsBuilder_ == null) {
        ensureStructsIsMutable();
        structs_.remove(index);
        onChanged();
      } else {
        structsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.StructSchema.Builder getStructsBuilder(
        int index) {
      return getStructsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.StructSchemaOrBuilder getStructsOrBuilder(
        int index) {
      if (structsBuilder_ == null) {
        return structs_.get(index);  } else {
        return structsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public java.util.List<? extends org.example.core.processor.bytedance.proto.StructSchemaOrBuilder> 
         getStructsOrBuilderList() {
      if (structsBuilder_ != null) {
        return structsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(structs_);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.StructSchema.Builder addStructsBuilder() {
      return getStructsFieldBuilder().addBuilder(
          org.example.core.processor.bytedance.proto.StructSchema.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public org.example.core.processor.bytedance.proto.StructSchema.Builder addStructsBuilder(
        int index) {
      return getStructsFieldBuilder().addBuilder(
          index, org.example.core.processor.bytedance.proto.StructSchema.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.StructSchema structs = 2;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.StructSchema.Builder> 
         getStructsBuilderList() {
      return getStructsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.StructSchema, org.example.core.processor.bytedance.proto.StructSchema.Builder, org.example.core.processor.bytedance.proto.StructSchemaOrBuilder> 
        getStructsFieldBuilder() {
      if (structsBuilder_ == null) {
        structsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.core.processor.bytedance.proto.StructSchema, org.example.core.processor.bytedance.proto.StructSchema.Builder, org.example.core.processor.bytedance.proto.StructSchemaOrBuilder>(
                structs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        structs_ = null;
      }
      return structsBuilder_;
    }

    private java.util.List<org.example.core.processor.bytedance.proto.Package> packages_ =
      java.util.Collections.emptyList();
    private void ensurePackagesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        packages_ = new java.util.ArrayList<org.example.core.processor.bytedance.proto.Package>(packages_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.Package, org.example.core.processor.bytedance.proto.Package.Builder, org.example.core.processor.bytedance.proto.PackageOrBuilder> packagesBuilder_;

    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.Package> getPackagesList() {
      if (packagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(packages_);
      } else {
        return packagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public int getPackagesCount() {
      if (packagesBuilder_ == null) {
        return packages_.size();
      } else {
        return packagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public org.example.core.processor.bytedance.proto.Package getPackages(int index) {
      if (packagesBuilder_ == null) {
        return packages_.get(index);
      } else {
        return packagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder setPackages(
        int index, org.example.core.processor.bytedance.proto.Package value) {
      if (packagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackagesIsMutable();
        packages_.set(index, value);
        onChanged();
      } else {
        packagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder setPackages(
        int index, org.example.core.processor.bytedance.proto.Package.Builder builderForValue) {
      if (packagesBuilder_ == null) {
        ensurePackagesIsMutable();
        packages_.set(index, builderForValue.build());
        onChanged();
      } else {
        packagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder addPackages(org.example.core.processor.bytedance.proto.Package value) {
      if (packagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackagesIsMutable();
        packages_.add(value);
        onChanged();
      } else {
        packagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder addPackages(
        int index, org.example.core.processor.bytedance.proto.Package value) {
      if (packagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackagesIsMutable();
        packages_.add(index, value);
        onChanged();
      } else {
        packagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder addPackages(
        org.example.core.processor.bytedance.proto.Package.Builder builderForValue) {
      if (packagesBuilder_ == null) {
        ensurePackagesIsMutable();
        packages_.add(builderForValue.build());
        onChanged();
      } else {
        packagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder addPackages(
        int index, org.example.core.processor.bytedance.proto.Package.Builder builderForValue) {
      if (packagesBuilder_ == null) {
        ensurePackagesIsMutable();
        packages_.add(index, builderForValue.build());
        onChanged();
      } else {
        packagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder addAllPackages(
        java.lang.Iterable<? extends org.example.core.processor.bytedance.proto.Package> values) {
      if (packagesBuilder_ == null) {
        ensurePackagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, packages_);
        onChanged();
      } else {
        packagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder clearPackages() {
      if (packagesBuilder_ == null) {
        packages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        packagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public Builder removePackages(int index) {
      if (packagesBuilder_ == null) {
        ensurePackagesIsMutable();
        packages_.remove(index);
        onChanged();
      } else {
        packagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public org.example.core.processor.bytedance.proto.Package.Builder getPackagesBuilder(
        int index) {
      return getPackagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public org.example.core.processor.bytedance.proto.PackageOrBuilder getPackagesOrBuilder(
        int index) {
      if (packagesBuilder_ == null) {
        return packages_.get(index);  } else {
        return packagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public java.util.List<? extends org.example.core.processor.bytedance.proto.PackageOrBuilder> 
         getPackagesOrBuilderList() {
      if (packagesBuilder_ != null) {
        return packagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(packages_);
      }
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public org.example.core.processor.bytedance.proto.Package.Builder addPackagesBuilder() {
      return getPackagesFieldBuilder().addBuilder(
          org.example.core.processor.bytedance.proto.Package.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public org.example.core.processor.bytedance.proto.Package.Builder addPackagesBuilder(
        int index) {
      return getPackagesFieldBuilder().addBuilder(
          index, org.example.core.processor.bytedance.proto.Package.getDefaultInstance());
    }
    /**
     * <code>repeated .security.sast.codegraph.repopb.Package packages = 4;</code>
     */
    public java.util.List<org.example.core.processor.bytedance.proto.Package.Builder> 
         getPackagesBuilderList() {
      return getPackagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.core.processor.bytedance.proto.Package, org.example.core.processor.bytedance.proto.Package.Builder, org.example.core.processor.bytedance.proto.PackageOrBuilder> 
        getPackagesFieldBuilder() {
      if (packagesBuilder_ == null) {
        packagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.core.processor.bytedance.proto.Package, org.example.core.processor.bytedance.proto.Package.Builder, org.example.core.processor.bytedance.proto.PackageOrBuilder>(
                packages_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        packages_ = null;
      }
      return packagesBuilder_;
    }

    private int language_ = 0;
    /**
     * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
     * @return The enum numeric value on the wire for language.
     */
    @java.lang.Override public int getLanguageValue() {
      return language_;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
     * @param value The enum numeric value on the wire for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageValue(int value) {
      language_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
     * @return The language.
     */
    @java.lang.Override
    public org.example.core.processor.bytedance.proto.Language getLanguage() {
      org.example.core.processor.bytedance.proto.Language result = org.example.core.processor.bytedance.proto.Language.forNumber(language_);
      return result == null ? org.example.core.processor.bytedance.proto.Language.UNRECOGNIZED : result;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(org.example.core.processor.bytedance.proto.Language value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      language_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.security.sast.codegraph.repopb.Language language = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      language_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.sast.codegraph.repopb.Repo)
  }

  // @@protoc_insertion_point(class_scope:security.sast.codegraph.repopb.Repo)
  private static final org.example.core.processor.bytedance.proto.Repo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.core.processor.bytedance.proto.Repo();
  }

  public static org.example.core.processor.bytedance.proto.Repo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Repo>
      PARSER = new com.google.protobuf.AbstractParser<Repo>() {
    @java.lang.Override
    public Repo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Repo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Repo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.core.processor.bytedance.proto.Repo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

