// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.processor.bytedance.proto;

public interface SetFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.SetField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 object_ptr_id = 1;</code>
   * @return The objectPtrId.
   */
  int getObjectPtrId();

  /**
   * <code>int32 value_id = 2;</code>
   * @return The valueId.
   */
  int getValueId();

  /**
   * <code>string name = 3;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 var_id = 4;</code>
   * @return Whether the varId field is set.
   */
  boolean hasVarId();
  /**
   * <code>int32 var_id = 4;</code>
   * @return The varId.
   */
  int getVarId();

  org.example.core.processor.bytedance.proto.SetField.FieldCase getFieldCase();
}
