// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package org.example.core.processor.bytedance.proto;

public interface StructSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.StructSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated .security.sast.codegraph.repopb.FieldSchema fields = 2;</code>
   */
  java.util.List<org.example.core.processor.bytedance.proto.FieldSchema> 
      getFieldsList();
  /**
   * <code>repeated .security.sast.codegraph.repopb.FieldSchema fields = 2;</code>
   */
  org.example.core.processor.bytedance.proto.FieldSchema getFields(int index);
  /**
   * <code>repeated .security.sast.codegraph.repopb.FieldSchema fields = 2;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .security.sast.codegraph.repopb.FieldSchema fields = 2;</code>
   */
  java.util.List<? extends org.example.core.processor.bytedance.proto.FieldSchemaOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .security.sast.codegraph.repopb.FieldSchema fields = 2;</code>
   */
  org.example.core.processor.bytedance.proto.FieldSchemaOrBuilder getFieldsOrBuilder(
      int index);
}
