// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rule.proto

package org.example.proto;

public final class RuleOuterClass {
  private RuleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rule.Sink)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The funcID.
     */
    java.lang.String getFuncID();
    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The bytes for funcID.
     */
    com.google.protobuf.ByteString
        getFuncIDBytes();

    /**
     * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     * @return The pos.
     */
    int getPos();
  }
  /**
   * Protobuf type {@code rule.Sink}
   */
  public static final class Sink extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rule.Sink)
      SinkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sink.newBuilder() to construct.
    private Sink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sink() {
      funcID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Sink();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.RuleOuterClass.internal_static_rule_Sink_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.RuleOuterClass.internal_static_rule_Sink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.RuleOuterClass.Sink.class, org.example.proto.RuleOuterClass.Sink.Builder.class);
    }

    public static final int FUNCID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object funcID_ = "";
    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The funcID.
     */
    @java.lang.Override
    public java.lang.String getFuncID() {
      java.lang.Object ref = funcID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        funcID_ = s;
        return s;
      }
    }
    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The bytes for funcID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFuncIDBytes() {
      java.lang.Object ref = funcID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        funcID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POS_FIELD_NUMBER = 2;
    private int pos_ = 0;
    /**
     * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     * @return The pos.
     */
    @java.lang.Override
    public int getPos() {
      return pos_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(funcID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, funcID_);
      }
      if (pos_ != 0) {
        output.writeInt32(2, pos_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(funcID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, funcID_);
      }
      if (pos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.RuleOuterClass.Sink)) {
        return super.equals(obj);
      }
      org.example.proto.RuleOuterClass.Sink other = (org.example.proto.RuleOuterClass.Sink) obj;

      if (!getFuncID()
          .equals(other.getFuncID())) return false;
      if (getPos()
          != other.getPos()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FUNCID_FIELD_NUMBER;
      hash = (53 * hash) + getFuncID().hashCode();
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + getPos();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Sink parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Sink parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Sink parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.RuleOuterClass.Sink prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rule.Sink}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rule.Sink)
        org.example.proto.RuleOuterClass.SinkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Sink_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Sink_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.RuleOuterClass.Sink.class, org.example.proto.RuleOuterClass.Sink.Builder.class);
      }

      // Construct using org.example.proto.RuleOuterClass.Sink.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        funcID_ = "";
        pos_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Sink_descriptor;
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Sink getDefaultInstanceForType() {
        return org.example.proto.RuleOuterClass.Sink.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Sink build() {
        org.example.proto.RuleOuterClass.Sink result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Sink buildPartial() {
        org.example.proto.RuleOuterClass.Sink result = new org.example.proto.RuleOuterClass.Sink(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.proto.RuleOuterClass.Sink result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.funcID_ = funcID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pos_ = pos_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.RuleOuterClass.Sink) {
          return mergeFrom((org.example.proto.RuleOuterClass.Sink)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.RuleOuterClass.Sink other) {
        if (other == org.example.proto.RuleOuterClass.Sink.getDefaultInstance()) return this;
        if (!other.getFuncID().isEmpty()) {
          funcID_ = other.funcID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getPos() != 0) {
          setPos(other.getPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                funcID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                pos_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object funcID_ = "";
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @return The funcID.
       */
      public java.lang.String getFuncID() {
        java.lang.Object ref = funcID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          funcID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @return The bytes for funcID.
       */
      public com.google.protobuf.ByteString
          getFuncIDBytes() {
        java.lang.Object ref = funcID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          funcID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @param value The funcID to set.
       * @return This builder for chaining.
       */
      public Builder setFuncID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        funcID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearFuncID() {
        funcID_ = getDefaultInstance().getFuncID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @param value The bytes for funcID to set.
       * @return This builder for chaining.
       */
      public Builder setFuncIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        funcID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int pos_ ;
      /**
       * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       * @return The pos.
       */
      @java.lang.Override
      public int getPos() {
        return pos_;
      }
      /**
       * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       * @param value The pos to set.
       * @return This builder for chaining.
       */
      public Builder setPos(int value) {
        
        pos_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearPos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pos_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rule.Sink)
    }

    // @@protoc_insertion_point(class_scope:rule.Sink)
    private static final org.example.proto.RuleOuterClass.Sink DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.RuleOuterClass.Sink();
    }

    public static org.example.proto.RuleOuterClass.Sink getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sink>
        PARSER = new com.google.protobuf.AbstractParser<Sink>() {
      @java.lang.Override
      public Sink parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sink> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sink> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.RuleOuterClass.Sink getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rule.Source)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The funcID.
     */
    java.lang.String getFuncID();
    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The bytes for funcID.
     */
    com.google.protobuf.ByteString
        getFuncIDBytes();

    /**
     * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     * @return The pos.
     */
    int getPos();
  }
  /**
   * Protobuf type {@code rule.Source}
   */
  public static final class Source extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rule.Source)
      SourceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Source.newBuilder() to construct.
    private Source(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Source() {
      funcID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Source();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.RuleOuterClass.internal_static_rule_Source_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.RuleOuterClass.internal_static_rule_Source_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.RuleOuterClass.Source.class, org.example.proto.RuleOuterClass.Source.Builder.class);
    }

    public static final int FUNCID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object funcID_ = "";
    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The funcID.
     */
    @java.lang.Override
    public java.lang.String getFuncID() {
      java.lang.Object ref = funcID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        funcID_ = s;
        return s;
      }
    }
    /**
     * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
     * @return The bytes for funcID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFuncIDBytes() {
      java.lang.Object ref = funcID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        funcID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POS_FIELD_NUMBER = 2;
    private int pos_ = 0;
    /**
     * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     * @return The pos.
     */
    @java.lang.Override
    public int getPos() {
      return pos_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(funcID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, funcID_);
      }
      if (pos_ != 0) {
        output.writeInt32(2, pos_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(funcID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, funcID_);
      }
      if (pos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.RuleOuterClass.Source)) {
        return super.equals(obj);
      }
      org.example.proto.RuleOuterClass.Source other = (org.example.proto.RuleOuterClass.Source) obj;

      if (!getFuncID()
          .equals(other.getFuncID())) return false;
      if (getPos()
          != other.getPos()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FUNCID_FIELD_NUMBER;
      hash = (53 * hash) + getFuncID().hashCode();
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + getPos();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.RuleOuterClass.Source parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Source parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Source parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Source parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.RuleOuterClass.Source prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rule.Source}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rule.Source)
        org.example.proto.RuleOuterClass.SourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Source_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Source_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.RuleOuterClass.Source.class, org.example.proto.RuleOuterClass.Source.Builder.class);
      }

      // Construct using org.example.proto.RuleOuterClass.Source.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        funcID_ = "";
        pos_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Source_descriptor;
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Source getDefaultInstanceForType() {
        return org.example.proto.RuleOuterClass.Source.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Source build() {
        org.example.proto.RuleOuterClass.Source result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Source buildPartial() {
        org.example.proto.RuleOuterClass.Source result = new org.example.proto.RuleOuterClass.Source(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.proto.RuleOuterClass.Source result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.funcID_ = funcID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pos_ = pos_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.RuleOuterClass.Source) {
          return mergeFrom((org.example.proto.RuleOuterClass.Source)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.RuleOuterClass.Source other) {
        if (other == org.example.proto.RuleOuterClass.Source.getDefaultInstance()) return this;
        if (!other.getFuncID().isEmpty()) {
          funcID_ = other.funcID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getPos() != 0) {
          setPos(other.getPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                funcID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                pos_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object funcID_ = "";
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @return The funcID.
       */
      public java.lang.String getFuncID() {
        java.lang.Object ref = funcID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          funcID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @return The bytes for funcID.
       */
      public com.google.protobuf.ByteString
          getFuncIDBytes() {
        java.lang.Object ref = funcID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          funcID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @param value The funcID to set.
       * @return This builder for chaining.
       */
      public Builder setFuncID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        funcID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearFuncID() {
        funcID_ = getDefaultInstance().getFuncID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string FuncID = 1 [(.gogoproto.jsontag) = "func_id", (.gogoproto.moretags) = "bson:&#92;"func_id&#92;""];</code>
       * @param value The bytes for funcID to set.
       * @return This builder for chaining.
       */
      public Builder setFuncIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        funcID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int pos_ ;
      /**
       * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       * @return The pos.
       */
      @java.lang.Override
      public int getPos() {
        return pos_;
      }
      /**
       * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       * @param value The pos to set.
       * @return This builder for chaining.
       */
      public Builder setPos(int value) {
        
        pos_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Pos = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearPos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pos_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rule.Source)
    }

    // @@protoc_insertion_point(class_scope:rule.Source)
    private static final org.example.proto.RuleOuterClass.Source DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.RuleOuterClass.Source();
    }

    public static org.example.proto.RuleOuterClass.Source getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Source>
        PARSER = new com.google.protobuf.AbstractParser<Source>() {
      @java.lang.Override
      public Source parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Source> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Source> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.RuleOuterClass.Source getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RuleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rule.Rule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    java.util.List<org.example.proto.RuleOuterClass.Source> 
        getSourcesList();
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    org.example.proto.RuleOuterClass.Source getSources(int index);
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    int getSourcesCount();
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    java.util.List<? extends org.example.proto.RuleOuterClass.SourceOrBuilder> 
        getSourcesOrBuilderList();
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    org.example.proto.RuleOuterClass.SourceOrBuilder getSourcesOrBuilder(
        int index);

    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    java.util.List<org.example.proto.RuleOuterClass.Sink> 
        getSinksList();
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    org.example.proto.RuleOuterClass.Sink getSinks(int index);
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    int getSinksCount();
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    java.util.List<? extends org.example.proto.RuleOuterClass.SinkOrBuilder> 
        getSinksOrBuilderList();
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    org.example.proto.RuleOuterClass.SinkOrBuilder getSinksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code rule.Rule}
   */
  public static final class Rule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rule.Rule)
      RuleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rule.newBuilder() to construct.
    private Rule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rule() {
      sources_ = java.util.Collections.emptyList();
      sinks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Rule();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.RuleOuterClass.internal_static_rule_Rule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.RuleOuterClass.internal_static_rule_Rule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.RuleOuterClass.Rule.class, org.example.proto.RuleOuterClass.Rule.Builder.class);
    }

    public static final int SOURCES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.example.proto.RuleOuterClass.Source> sources_;
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    @java.lang.Override
    public java.util.List<org.example.proto.RuleOuterClass.Source> getSourcesList() {
      return sources_;
    }
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.example.proto.RuleOuterClass.SourceOrBuilder> 
        getSourcesOrBuilderList() {
      return sources_;
    }
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    @java.lang.Override
    public int getSourcesCount() {
      return sources_.size();
    }
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    @java.lang.Override
    public org.example.proto.RuleOuterClass.Source getSources(int index) {
      return sources_.get(index);
    }
    /**
     * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
     */
    @java.lang.Override
    public org.example.proto.RuleOuterClass.SourceOrBuilder getSourcesOrBuilder(
        int index) {
      return sources_.get(index);
    }

    public static final int SINKS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<org.example.proto.RuleOuterClass.Sink> sinks_;
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    @java.lang.Override
    public java.util.List<org.example.proto.RuleOuterClass.Sink> getSinksList() {
      return sinks_;
    }
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.example.proto.RuleOuterClass.SinkOrBuilder> 
        getSinksOrBuilderList() {
      return sinks_;
    }
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    @java.lang.Override
    public int getSinksCount() {
      return sinks_.size();
    }
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    @java.lang.Override
    public org.example.proto.RuleOuterClass.Sink getSinks(int index) {
      return sinks_.get(index);
    }
    /**
     * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
     */
    @java.lang.Override
    public org.example.proto.RuleOuterClass.SinkOrBuilder getSinksOrBuilder(
        int index) {
      return sinks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sources_.size(); i++) {
        output.writeMessage(1, sources_.get(i));
      }
      for (int i = 0; i < sinks_.size(); i++) {
        output.writeMessage(2, sinks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sources_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sources_.get(i));
      }
      for (int i = 0; i < sinks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, sinks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.RuleOuterClass.Rule)) {
        return super.equals(obj);
      }
      org.example.proto.RuleOuterClass.Rule other = (org.example.proto.RuleOuterClass.Rule) obj;

      if (!getSourcesList()
          .equals(other.getSourcesList())) return false;
      if (!getSinksList()
          .equals(other.getSinksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSourcesCount() > 0) {
        hash = (37 * hash) + SOURCES_FIELD_NUMBER;
        hash = (53 * hash) + getSourcesList().hashCode();
      }
      if (getSinksCount() > 0) {
        hash = (37 * hash) + SINKS_FIELD_NUMBER;
        hash = (53 * hash) + getSinksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Rule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Rule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.RuleOuterClass.Rule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.RuleOuterClass.Rule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rule.Rule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rule.Rule)
        org.example.proto.RuleOuterClass.RuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Rule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Rule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.RuleOuterClass.Rule.class, org.example.proto.RuleOuterClass.Rule.Builder.class);
      }

      // Construct using org.example.proto.RuleOuterClass.Rule.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (sourcesBuilder_ == null) {
          sources_ = java.util.Collections.emptyList();
        } else {
          sources_ = null;
          sourcesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (sinksBuilder_ == null) {
          sinks_ = java.util.Collections.emptyList();
        } else {
          sinks_ = null;
          sinksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.RuleOuterClass.internal_static_rule_Rule_descriptor;
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Rule getDefaultInstanceForType() {
        return org.example.proto.RuleOuterClass.Rule.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Rule build() {
        org.example.proto.RuleOuterClass.Rule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.RuleOuterClass.Rule buildPartial() {
        org.example.proto.RuleOuterClass.Rule result = new org.example.proto.RuleOuterClass.Rule(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.example.proto.RuleOuterClass.Rule result) {
        if (sourcesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            sources_ = java.util.Collections.unmodifiableList(sources_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sources_ = sources_;
        } else {
          result.sources_ = sourcesBuilder_.build();
        }
        if (sinksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            sinks_ = java.util.Collections.unmodifiableList(sinks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.sinks_ = sinks_;
        } else {
          result.sinks_ = sinksBuilder_.build();
        }
      }

      private void buildPartial0(org.example.proto.RuleOuterClass.Rule result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.RuleOuterClass.Rule) {
          return mergeFrom((org.example.proto.RuleOuterClass.Rule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.RuleOuterClass.Rule other) {
        if (other == org.example.proto.RuleOuterClass.Rule.getDefaultInstance()) return this;
        if (sourcesBuilder_ == null) {
          if (!other.sources_.isEmpty()) {
            if (sources_.isEmpty()) {
              sources_ = other.sources_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSourcesIsMutable();
              sources_.addAll(other.sources_);
            }
            onChanged();
          }
        } else {
          if (!other.sources_.isEmpty()) {
            if (sourcesBuilder_.isEmpty()) {
              sourcesBuilder_.dispose();
              sourcesBuilder_ = null;
              sources_ = other.sources_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sourcesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSourcesFieldBuilder() : null;
            } else {
              sourcesBuilder_.addAllMessages(other.sources_);
            }
          }
        }
        if (sinksBuilder_ == null) {
          if (!other.sinks_.isEmpty()) {
            if (sinks_.isEmpty()) {
              sinks_ = other.sinks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSinksIsMutable();
              sinks_.addAll(other.sinks_);
            }
            onChanged();
          }
        } else {
          if (!other.sinks_.isEmpty()) {
            if (sinksBuilder_.isEmpty()) {
              sinksBuilder_.dispose();
              sinksBuilder_ = null;
              sinks_ = other.sinks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              sinksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSinksFieldBuilder() : null;
            } else {
              sinksBuilder_.addAllMessages(other.sinks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.example.proto.RuleOuterClass.Source m =
                    input.readMessage(
                        org.example.proto.RuleOuterClass.Source.parser(),
                        extensionRegistry);
                if (sourcesBuilder_ == null) {
                  ensureSourcesIsMutable();
                  sources_.add(m);
                } else {
                  sourcesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                org.example.proto.RuleOuterClass.Sink m =
                    input.readMessage(
                        org.example.proto.RuleOuterClass.Sink.parser(),
                        extensionRegistry);
                if (sinksBuilder_ == null) {
                  ensureSinksIsMutable();
                  sinks_.add(m);
                } else {
                  sinksBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.example.proto.RuleOuterClass.Source> sources_ =
        java.util.Collections.emptyList();
      private void ensureSourcesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          sources_ = new java.util.ArrayList<org.example.proto.RuleOuterClass.Source>(sources_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.example.proto.RuleOuterClass.Source, org.example.proto.RuleOuterClass.Source.Builder, org.example.proto.RuleOuterClass.SourceOrBuilder> sourcesBuilder_;

      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public java.util.List<org.example.proto.RuleOuterClass.Source> getSourcesList() {
        if (sourcesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sources_);
        } else {
          return sourcesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public int getSourcesCount() {
        if (sourcesBuilder_ == null) {
          return sources_.size();
        } else {
          return sourcesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Source getSources(int index) {
        if (sourcesBuilder_ == null) {
          return sources_.get(index);
        } else {
          return sourcesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder setSources(
          int index, org.example.proto.RuleOuterClass.Source value) {
        if (sourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSourcesIsMutable();
          sources_.set(index, value);
          onChanged();
        } else {
          sourcesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder setSources(
          int index, org.example.proto.RuleOuterClass.Source.Builder builderForValue) {
        if (sourcesBuilder_ == null) {
          ensureSourcesIsMutable();
          sources_.set(index, builderForValue.build());
          onChanged();
        } else {
          sourcesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder addSources(org.example.proto.RuleOuterClass.Source value) {
        if (sourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSourcesIsMutable();
          sources_.add(value);
          onChanged();
        } else {
          sourcesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder addSources(
          int index, org.example.proto.RuleOuterClass.Source value) {
        if (sourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSourcesIsMutable();
          sources_.add(index, value);
          onChanged();
        } else {
          sourcesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder addSources(
          org.example.proto.RuleOuterClass.Source.Builder builderForValue) {
        if (sourcesBuilder_ == null) {
          ensureSourcesIsMutable();
          sources_.add(builderForValue.build());
          onChanged();
        } else {
          sourcesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder addSources(
          int index, org.example.proto.RuleOuterClass.Source.Builder builderForValue) {
        if (sourcesBuilder_ == null) {
          ensureSourcesIsMutable();
          sources_.add(index, builderForValue.build());
          onChanged();
        } else {
          sourcesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder addAllSources(
          java.lang.Iterable<? extends org.example.proto.RuleOuterClass.Source> values) {
        if (sourcesBuilder_ == null) {
          ensureSourcesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sources_);
          onChanged();
        } else {
          sourcesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder clearSources() {
        if (sourcesBuilder_ == null) {
          sources_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sourcesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public Builder removeSources(int index) {
        if (sourcesBuilder_ == null) {
          ensureSourcesIsMutable();
          sources_.remove(index);
          onChanged();
        } else {
          sourcesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Source.Builder getSourcesBuilder(
          int index) {
        return getSourcesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.SourceOrBuilder getSourcesOrBuilder(
          int index) {
        if (sourcesBuilder_ == null) {
          return sources_.get(index);  } else {
          return sourcesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public java.util.List<? extends org.example.proto.RuleOuterClass.SourceOrBuilder> 
           getSourcesOrBuilderList() {
        if (sourcesBuilder_ != null) {
          return sourcesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sources_);
        }
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Source.Builder addSourcesBuilder() {
        return getSourcesFieldBuilder().addBuilder(
            org.example.proto.RuleOuterClass.Source.getDefaultInstance());
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Source.Builder addSourcesBuilder(
          int index) {
        return getSourcesFieldBuilder().addBuilder(
            index, org.example.proto.RuleOuterClass.Source.getDefaultInstance());
      }
      /**
       * <code>repeated .rule.Source Sources = 1 [(.gogoproto.jsontag) = "sources", (.gogoproto.moretags) = "bson:&#92;"sources&#92;""];</code>
       */
      public java.util.List<org.example.proto.RuleOuterClass.Source.Builder> 
           getSourcesBuilderList() {
        return getSourcesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.example.proto.RuleOuterClass.Source, org.example.proto.RuleOuterClass.Source.Builder, org.example.proto.RuleOuterClass.SourceOrBuilder> 
          getSourcesFieldBuilder() {
        if (sourcesBuilder_ == null) {
          sourcesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.example.proto.RuleOuterClass.Source, org.example.proto.RuleOuterClass.Source.Builder, org.example.proto.RuleOuterClass.SourceOrBuilder>(
                  sources_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          sources_ = null;
        }
        return sourcesBuilder_;
      }

      private java.util.List<org.example.proto.RuleOuterClass.Sink> sinks_ =
        java.util.Collections.emptyList();
      private void ensureSinksIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          sinks_ = new java.util.ArrayList<org.example.proto.RuleOuterClass.Sink>(sinks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.example.proto.RuleOuterClass.Sink, org.example.proto.RuleOuterClass.Sink.Builder, org.example.proto.RuleOuterClass.SinkOrBuilder> sinksBuilder_;

      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public java.util.List<org.example.proto.RuleOuterClass.Sink> getSinksList() {
        if (sinksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sinks_);
        } else {
          return sinksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public int getSinksCount() {
        if (sinksBuilder_ == null) {
          return sinks_.size();
        } else {
          return sinksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Sink getSinks(int index) {
        if (sinksBuilder_ == null) {
          return sinks_.get(index);
        } else {
          return sinksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder setSinks(
          int index, org.example.proto.RuleOuterClass.Sink value) {
        if (sinksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSinksIsMutable();
          sinks_.set(index, value);
          onChanged();
        } else {
          sinksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder setSinks(
          int index, org.example.proto.RuleOuterClass.Sink.Builder builderForValue) {
        if (sinksBuilder_ == null) {
          ensureSinksIsMutable();
          sinks_.set(index, builderForValue.build());
          onChanged();
        } else {
          sinksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder addSinks(org.example.proto.RuleOuterClass.Sink value) {
        if (sinksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSinksIsMutable();
          sinks_.add(value);
          onChanged();
        } else {
          sinksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder addSinks(
          int index, org.example.proto.RuleOuterClass.Sink value) {
        if (sinksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSinksIsMutable();
          sinks_.add(index, value);
          onChanged();
        } else {
          sinksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder addSinks(
          org.example.proto.RuleOuterClass.Sink.Builder builderForValue) {
        if (sinksBuilder_ == null) {
          ensureSinksIsMutable();
          sinks_.add(builderForValue.build());
          onChanged();
        } else {
          sinksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder addSinks(
          int index, org.example.proto.RuleOuterClass.Sink.Builder builderForValue) {
        if (sinksBuilder_ == null) {
          ensureSinksIsMutable();
          sinks_.add(index, builderForValue.build());
          onChanged();
        } else {
          sinksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder addAllSinks(
          java.lang.Iterable<? extends org.example.proto.RuleOuterClass.Sink> values) {
        if (sinksBuilder_ == null) {
          ensureSinksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sinks_);
          onChanged();
        } else {
          sinksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder clearSinks() {
        if (sinksBuilder_ == null) {
          sinks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          sinksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public Builder removeSinks(int index) {
        if (sinksBuilder_ == null) {
          ensureSinksIsMutable();
          sinks_.remove(index);
          onChanged();
        } else {
          sinksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Sink.Builder getSinksBuilder(
          int index) {
        return getSinksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.SinkOrBuilder getSinksOrBuilder(
          int index) {
        if (sinksBuilder_ == null) {
          return sinks_.get(index);  } else {
          return sinksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public java.util.List<? extends org.example.proto.RuleOuterClass.SinkOrBuilder> 
           getSinksOrBuilderList() {
        if (sinksBuilder_ != null) {
          return sinksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sinks_);
        }
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Sink.Builder addSinksBuilder() {
        return getSinksFieldBuilder().addBuilder(
            org.example.proto.RuleOuterClass.Sink.getDefaultInstance());
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public org.example.proto.RuleOuterClass.Sink.Builder addSinksBuilder(
          int index) {
        return getSinksFieldBuilder().addBuilder(
            index, org.example.proto.RuleOuterClass.Sink.getDefaultInstance());
      }
      /**
       * <code>repeated .rule.Sink Sinks = 2 [(.gogoproto.jsontag) = "pos", (.gogoproto.moretags) = "bson:&#92;"pos&#92;""];</code>
       */
      public java.util.List<org.example.proto.RuleOuterClass.Sink.Builder> 
           getSinksBuilderList() {
        return getSinksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.example.proto.RuleOuterClass.Sink, org.example.proto.RuleOuterClass.Sink.Builder, org.example.proto.RuleOuterClass.SinkOrBuilder> 
          getSinksFieldBuilder() {
        if (sinksBuilder_ == null) {
          sinksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.example.proto.RuleOuterClass.Sink, org.example.proto.RuleOuterClass.Sink.Builder, org.example.proto.RuleOuterClass.SinkOrBuilder>(
                  sinks_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          sinks_ = null;
        }
        return sinksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rule.Rule)
    }

    // @@protoc_insertion_point(class_scope:rule.Rule)
    private static final org.example.proto.RuleOuterClass.Rule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.RuleOuterClass.Rule();
    }

    public static org.example.proto.RuleOuterClass.Rule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rule>
        PARSER = new com.google.protobuf.AbstractParser<Rule>() {
      @java.lang.Override
      public Rule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Rule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rule> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.RuleOuterClass.Rule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rule_Sink_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rule_Sink_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rule_Source_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rule_Source_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rule_Rule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rule_Rule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrule.proto\022\004rule\032\ngogo.proto\"Y\n\004Sink\022-" +
      "\n\006FuncID\030\001 \001(\tB\035\352\336\037\007func_id\362\336\037\016bson:\"fun" +
      "c_id\"\022\"\n\003Pos\030\002 \001(\005B\025\352\336\037\003pos\362\336\037\nbson:\"pos" +
      "\"\"[\n\006Source\022-\n\006FuncID\030\001 \001(\tB\035\352\336\037\007func_id" +
      "\362\336\037\016bson:\"func_id\"\022\"\n\003Pos\030\002 \001(\005B\025\352\336\037\003pos" +
      "\362\336\037\nbson:\"pos\"\"v\n\004Rule\022<\n\007Sources\030\001 \003(\0132" +
      "\014.rule.SourceB\035\352\336\037\007sources\362\336\037\016bson:\"sour" +
      "ces\"\0220\n\005Sinks\030\002 \003(\0132\n.rule.SinkB\025\352\336\037\003pos" +
      "\362\336\037\nbson:\"pos\"B\033\n\021org.example.protoZ\002./\370" +
      "\341\036\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_rule_Sink_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rule_Sink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rule_Sink_descriptor,
        new java.lang.String[] { "FuncID", "Pos", });
    internal_static_rule_Source_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rule_Source_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rule_Source_descriptor,
        new java.lang.String[] { "FuncID", "Pos", });
    internal_static_rule_Rule_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rule_Rule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rule_Rule_descriptor,
        new java.lang.String[] { "Sources", "Sinks", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.jsontag);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.populateAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
