// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

public interface CallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.Call)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 arg_ids = 2;</code>
   * @return A list containing the argIds.
   */
  java.util.List<java.lang.Integer> getArgIdsList();
  /**
   * <code>repeated int32 arg_ids = 2;</code>
   * @return The count of argIds.
   */
  int getArgIdsCount();
  /**
   * <code>repeated int32 arg_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The argIds at the given index.
   */
  int getArgIds(int index);

  /**
   * <code>repeated int32 ret_ids = 4;</code>
   * @return A list containing the retIds.
   */
  java.util.List<java.lang.Integer> getRetIdsList();
  /**
   * <code>repeated int32 ret_ids = 4;</code>
   * @return The count of retIds.
   */
  int getRetIdsCount();
  /**
   * <code>repeated int32 ret_ids = 4;</code>
   * @param index The index of the element to return.
   * @return The retIds at the given index.
   */
  int getRetIds(int index);

  /**
   * <code>string static_func_name = 9;</code>
   * @return Whether the staticFuncName field is set.
   */
  boolean hasStaticFuncName();
  /**
   * <code>string static_func_name = 9;</code>
   * @return The staticFuncName.
   */
  java.lang.String getStaticFuncName();
  /**
   * <code>string static_func_name = 9;</code>
   * @return The bytes for staticFuncName.
   */
  com.google.protobuf.ByteString
      getStaticFuncNameBytes();

  /**
   * <code>int32 dynamic_func_id = 10;</code>
   * @return Whether the dynamicFuncId field is set.
   */
  boolean hasDynamicFuncId();
  /**
   * <code>int32 dynamic_func_id = 10;</code>
   * @return The dynamicFuncId.
   */
  int getDynamicFuncId();

  /**
   * <code>string invoke_method_name = 11;</code>
   * @return Whether the invokeMethodName field is set.
   */
  boolean hasInvokeMethodName();
  /**
   * <code>string invoke_method_name = 11;</code>
   * @return The invokeMethodName.
   */
  java.lang.String getInvokeMethodName();
  /**
   * <code>string invoke_method_name = 11;</code>
   * @return The bytes for invokeMethodName.
   */
  com.google.protobuf.ByteString
      getInvokeMethodNameBytes();

  Call.RefCase getRefCase();
}
