// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package org.example.core.hook.bytedance.proto;

public final class CodeGraphType {
  private CodeGraphType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_StructSchema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_StructSchema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_sast_codegraph_repopb_FieldSchema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_sast_codegraph_repopb_FieldSchema_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntype.proto\022\036security.sast.codegraph.re" +
      "popb\"W\n\014StructSchema\022\n\n\002id\030\001 \001(\t\022;\n\006fiel" +
      "ds\030\002 \003(\0132+.security.sast.codegraph.repop" +
      "b.FieldSchema\"F\n\013FieldSchema\022\014\n\004name\030\001 \001" +
      "(\t\022\r\n\005index\030\002 \001(\005\022\014\n\004type\030\003 \001(\t\022\014\n\004tags\030" +
      "\004 \001(\tB=\n*org.example.core.processor.byte" +
      "dance.protoB\rCodeGraphTypeP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_security_sast_codegraph_repopb_StructSchema_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_security_sast_codegraph_repopb_StructSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_StructSchema_descriptor,
        new java.lang.String[] { "Id", "Fields", });
    internal_static_security_sast_codegraph_repopb_FieldSchema_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_security_sast_codegraph_repopb_FieldSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_sast_codegraph_repopb_FieldSchema_descriptor,
        new java.lang.String[] { "Name", "Index", "Type", "Tags", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
