// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo.proto

package org.example.core.hook.bytedance.proto;

/**
 * Protobuf type {@code security.sast.codegraph.repopb.FuncSignature}
 */
public final class FuncSignature extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.sast.codegraph.repopb.FuncSignature)
    FuncSignatureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FuncSignature.newBuilder() to construct.
  private FuncSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FuncSignature() {
    classType_ = "";
    argTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    retTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FuncSignature();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CodeGraphRepo.internal_static_security_sast_codegraph_repopb_FuncSignature_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CodeGraphRepo.internal_static_security_sast_codegraph_repopb_FuncSignature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FuncSignature.class, FuncSignature.Builder.class);
  }

  public static final int CLASS_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object classType_ = "";
  /**
   * <pre>
   * if the function is a method
   * </pre>
   *
   * <code>string class_type = 1;</code>
   * @return The classType.
   */
  @java.lang.Override
  public java.lang.String getClassType() {
    java.lang.Object ref = classType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      classType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * if the function is a method
   * </pre>
   *
   * <code>string class_type = 1;</code>
   * @return The bytes for classType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClassTypeBytes() {
    java.lang.Object ref = classType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      classType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARG_TYPES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList argTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string arg_types = 2;</code>
   * @return A list containing the argTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getArgTypesList() {
    return argTypes_;
  }
  /**
   * <code>repeated string arg_types = 2;</code>
   * @return The count of argTypes.
   */
  public int getArgTypesCount() {
    return argTypes_.size();
  }
  /**
   * <code>repeated string arg_types = 2;</code>
   * @param index The index of the element to return.
   * @return The argTypes at the given index.
   */
  public java.lang.String getArgTypes(int index) {
    return argTypes_.get(index);
  }
  /**
   * <code>repeated string arg_types = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the argTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getArgTypesBytes(int index) {
    return argTypes_.getByteString(index);
  }

  public static final int RET_TYPES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList retTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string ret_types = 3;</code>
   * @return A list containing the retTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getRetTypesList() {
    return retTypes_;
  }
  /**
   * <code>repeated string ret_types = 3;</code>
   * @return The count of retTypes.
   */
  public int getRetTypesCount() {
    return retTypes_.size();
  }
  /**
   * <code>repeated string ret_types = 3;</code>
   * @param index The index of the element to return.
   * @return The retTypes at the given index.
   */
  public java.lang.String getRetTypes(int index) {
    return retTypes_.get(index);
  }
  /**
   * <code>repeated string ret_types = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the retTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getRetTypesBytes(int index) {
    return retTypes_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(classType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, classType_);
    }
    for (int i = 0; i < argTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, argTypes_.getRaw(i));
    }
    for (int i = 0; i < retTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, retTypes_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(classType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, classType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < argTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(argTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getArgTypesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < retTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(retTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRetTypesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FuncSignature)) {
      return super.equals(obj);
    }
    FuncSignature other = (FuncSignature) obj;

    if (!getClassType()
        .equals(other.getClassType())) return false;
    if (!getArgTypesList()
        .equals(other.getArgTypesList())) return false;
    if (!getRetTypesList()
        .equals(other.getRetTypesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLASS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getClassType().hashCode();
    if (getArgTypesCount() > 0) {
      hash = (37 * hash) + ARG_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getArgTypesList().hashCode();
    }
    if (getRetTypesCount() > 0) {
      hash = (37 * hash) + RET_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getRetTypesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FuncSignature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FuncSignature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FuncSignature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FuncSignature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FuncSignature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FuncSignature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FuncSignature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FuncSignature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static FuncSignature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static FuncSignature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FuncSignature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FuncSignature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FuncSignature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code security.sast.codegraph.repopb.FuncSignature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.sast.codegraph.repopb.FuncSignature)
          FuncSignatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CodeGraphRepo.internal_static_security_sast_codegraph_repopb_FuncSignature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CodeGraphRepo.internal_static_security_sast_codegraph_repopb_FuncSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FuncSignature.class, FuncSignature.Builder.class);
    }

    // Construct using org.example.core.processor.bytedance.proto.FuncSignature.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      classType_ = "";
      argTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      retTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CodeGraphRepo.internal_static_security_sast_codegraph_repopb_FuncSignature_descriptor;
    }

    @java.lang.Override
    public FuncSignature getDefaultInstanceForType() {
      return FuncSignature.getDefaultInstance();
    }

    @java.lang.Override
    public FuncSignature build() {
      FuncSignature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public FuncSignature buildPartial() {
      FuncSignature result = new FuncSignature(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(FuncSignature result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.classType_ = classType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        argTypes_.makeImmutable();
        result.argTypes_ = argTypes_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        retTypes_.makeImmutable();
        result.retTypes_ = retTypes_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FuncSignature) {
        return mergeFrom((FuncSignature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FuncSignature other) {
      if (other == FuncSignature.getDefaultInstance()) return this;
      if (!other.getClassType().isEmpty()) {
        classType_ = other.classType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.argTypes_.isEmpty()) {
        if (argTypes_.isEmpty()) {
          argTypes_ = other.argTypes_;
          bitField0_ |= 0x00000002;
        } else {
          ensureArgTypesIsMutable();
          argTypes_.addAll(other.argTypes_);
        }
        onChanged();
      }
      if (!other.retTypes_.isEmpty()) {
        if (retTypes_.isEmpty()) {
          retTypes_ = other.retTypes_;
          bitField0_ |= 0x00000004;
        } else {
          ensureRetTypesIsMutable();
          retTypes_.addAll(other.retTypes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              classType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureArgTypesIsMutable();
              argTypes_.add(s);
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRetTypesIsMutable();
              retTypes_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object classType_ = "";
    /**
     * <pre>
     * if the function is a method
     * </pre>
     *
     * <code>string class_type = 1;</code>
     * @return The classType.
     */
    public java.lang.String getClassType() {
      java.lang.Object ref = classType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        classType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * if the function is a method
     * </pre>
     *
     * <code>string class_type = 1;</code>
     * @return The bytes for classType.
     */
    public com.google.protobuf.ByteString
        getClassTypeBytes() {
      java.lang.Object ref = classType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * if the function is a method
     * </pre>
     *
     * <code>string class_type = 1;</code>
     * @param value The classType to set.
     * @return This builder for chaining.
     */
    public Builder setClassType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      classType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if the function is a method
     * </pre>
     *
     * <code>string class_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassType() {
      classType_ = getDefaultInstance().getClassType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if the function is a method
     * </pre>
     *
     * <code>string class_type = 1;</code>
     * @param value The bytes for classType to set.
     * @return This builder for chaining.
     */
    public Builder setClassTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      classType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList argTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureArgTypesIsMutable() {
      if (!argTypes_.isModifiable()) {
        argTypes_ = new com.google.protobuf.LazyStringArrayList(argTypes_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @return A list containing the argTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getArgTypesList() {
      argTypes_.makeImmutable();
      return argTypes_;
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @return The count of argTypes.
     */
    public int getArgTypesCount() {
      return argTypes_.size();
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @param index The index of the element to return.
     * @return The argTypes at the given index.
     */
    public java.lang.String getArgTypes(int index) {
      return argTypes_.get(index);
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the argTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getArgTypesBytes(int index) {
      return argTypes_.getByteString(index);
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @param index The index to set the value at.
     * @param value The argTypes to set.
     * @return This builder for chaining.
     */
    public Builder setArgTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureArgTypesIsMutable();
      argTypes_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @param value The argTypes to add.
     * @return This builder for chaining.
     */
    public Builder addArgTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureArgTypesIsMutable();
      argTypes_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @param values The argTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllArgTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureArgTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, argTypes_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearArgTypes() {
      argTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arg_types = 2;</code>
     * @param value The bytes of the argTypes to add.
     * @return This builder for chaining.
     */
    public Builder addArgTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureArgTypesIsMutable();
      argTypes_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList retTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRetTypesIsMutable() {
      if (!retTypes_.isModifiable()) {
        retTypes_ = new com.google.protobuf.LazyStringArrayList(retTypes_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @return A list containing the retTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getRetTypesList() {
      retTypes_.makeImmutable();
      return retTypes_;
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @return The count of retTypes.
     */
    public int getRetTypesCount() {
      return retTypes_.size();
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @param index The index of the element to return.
     * @return The retTypes at the given index.
     */
    public java.lang.String getRetTypes(int index) {
      return retTypes_.get(index);
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the retTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getRetTypesBytes(int index) {
      return retTypes_.getByteString(index);
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @param index The index to set the value at.
     * @param value The retTypes to set.
     * @return This builder for chaining.
     */
    public Builder setRetTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRetTypesIsMutable();
      retTypes_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @param value The retTypes to add.
     * @return This builder for chaining.
     */
    public Builder addRetTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRetTypesIsMutable();
      retTypes_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @param values The retTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllRetTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureRetTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, retTypes_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetTypes() {
      retTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ret_types = 3;</code>
     * @param value The bytes of the retTypes to add.
     * @return This builder for chaining.
     */
    public Builder addRetTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRetTypesIsMutable();
      retTypes_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.sast.codegraph.repopb.FuncSignature)
  }

  // @@protoc_insertion_point(class_scope:security.sast.codegraph.repopb.FuncSignature)
  private static final FuncSignature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FuncSignature();
  }

  public static FuncSignature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FuncSignature>
      PARSER = new com.google.protobuf.AbstractParser<FuncSignature>() {
    @java.lang.Override
    public FuncSignature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FuncSignature> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FuncSignature> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public FuncSignature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

