// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

public interface GetFieldAddrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.GetFieldAddr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ptr_id = 1;</code>
   * @return The ptrId.
   */
  int getPtrId();

  /**
   * <code>int32 object_ptr_id = 2;</code>
   * @return The objectPtrId.
   */
  int getObjectPtrId();

  /**
   * <code>string name = 3;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 var_id = 4;</code>
   * @return Whether the varId field is set.
   */
  boolean hasVarId();
  /**
   * <code>int32 var_id = 4;</code>
   * @return The varId.
   */
  int getVarId();

  /**
   * <code>bool merge_all = 5;</code>
   * @return Whether the mergeAll field is set.
   */
  boolean hasMergeAll();
  /**
   * <code>bool merge_all = 5;</code>
   * @return The mergeAll.
   */
  boolean getMergeAll();

  GetFieldAddr.FieldCase getFieldCase();
}
