// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

public interface LoadPtrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.LoadPtr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 target_id = 1;</code>
   * @return The targetId.
   */
  int getTargetId();

  /**
   * <code>int32 ptr_id = 2;</code>
   * @return The ptrId.
   */
  int getPtrId();
}
