// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

/**
 * <pre>
 * MakeClosure bind free variables of closure `func`, store the result to `target`
 * </pre>
 *
 * Protobuf type {@code security.sast.codegraph.repopb.MakeClosure}
 */
public final class MakeClosure extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.sast.codegraph.repopb.MakeClosure)
    MakeClosureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MakeClosure.newBuilder() to construct.
  private MakeClosure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MakeClosure() {
    bindingIds_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MakeClosure();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_MakeClosure_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_MakeClosure_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MakeClosure.class, MakeClosure.Builder.class);
  }

  public static final int TARGET_ID_FIELD_NUMBER = 1;
  private int targetId_ = 0;
  /**
   * <code>int32 target_id = 1;</code>
   * @return The targetId.
   */
  @java.lang.Override
  public int getTargetId() {
    return targetId_;
  }

  public static final int FUNC_ID_FIELD_NUMBER = 2;
  private int funcId_ = 0;
  /**
   * <code>int32 func_id = 2;</code>
   * @return The funcId.
   */
  @java.lang.Override
  public int getFuncId() {
    return funcId_;
  }

  public static final int BINDING_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList bindingIds_;
  /**
   * <code>repeated int32 binding_ids = 3;</code>
   * @return A list containing the bindingIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getBindingIdsList() {
    return bindingIds_;
  }
  /**
   * <code>repeated int32 binding_ids = 3;</code>
   * @return The count of bindingIds.
   */
  public int getBindingIdsCount() {
    return bindingIds_.size();
  }
  /**
   * <code>repeated int32 binding_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The bindingIds at the given index.
   */
  public int getBindingIds(int index) {
    return bindingIds_.getInt(index);
  }
  private int bindingIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (targetId_ != 0) {
      output.writeInt32(1, targetId_);
    }
    if (funcId_ != 0) {
      output.writeInt32(2, funcId_);
    }
    if (getBindingIdsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(bindingIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < bindingIds_.size(); i++) {
      output.writeInt32NoTag(bindingIds_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (targetId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, targetId_);
    }
    if (funcId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, funcId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < bindingIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(bindingIds_.getInt(i));
      }
      size += dataSize;
      if (!getBindingIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      bindingIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MakeClosure)) {
      return super.equals(obj);
    }
    MakeClosure other = (MakeClosure) obj;

    if (getTargetId()
        != other.getTargetId()) return false;
    if (getFuncId()
        != other.getFuncId()) return false;
    if (!getBindingIdsList()
        .equals(other.getBindingIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetId();
    hash = (37 * hash) + FUNC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFuncId();
    if (getBindingIdsCount() > 0) {
      hash = (37 * hash) + BINDING_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getBindingIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MakeClosure parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MakeClosure parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MakeClosure parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MakeClosure parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MakeClosure parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MakeClosure parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MakeClosure parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MakeClosure parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static MakeClosure parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static MakeClosure parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MakeClosure parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MakeClosure parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MakeClosure prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MakeClosure bind free variables of closure `func`, store the result to `target`
   * </pre>
   *
   * Protobuf type {@code security.sast.codegraph.repopb.MakeClosure}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.sast.codegraph.repopb.MakeClosure)
          MakeClosureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_MakeClosure_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_MakeClosure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MakeClosure.class, MakeClosure.Builder.class);
    }

    // Construct using org.example.core.processor.bytedance.proto.MakeClosure.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      targetId_ = 0;
      funcId_ = 0;
      bindingIds_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_MakeClosure_descriptor;
    }

    @java.lang.Override
    public MakeClosure getDefaultInstanceForType() {
      return MakeClosure.getDefaultInstance();
    }

    @java.lang.Override
    public MakeClosure build() {
      MakeClosure result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MakeClosure buildPartial() {
      MakeClosure result = new MakeClosure(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(MakeClosure result) {
      if (((bitField0_ & 0x00000004) != 0)) {
        bindingIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.bindingIds_ = bindingIds_;
    }

    private void buildPartial0(MakeClosure result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.targetId_ = targetId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.funcId_ = funcId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MakeClosure) {
        return mergeFrom((MakeClosure)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MakeClosure other) {
      if (other == MakeClosure.getDefaultInstance()) return this;
      if (other.getTargetId() != 0) {
        setTargetId(other.getTargetId());
      }
      if (other.getFuncId() != 0) {
        setFuncId(other.getFuncId());
      }
      if (!other.bindingIds_.isEmpty()) {
        if (bindingIds_.isEmpty()) {
          bindingIds_ = other.bindingIds_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureBindingIdsIsMutable();
          bindingIds_.addAll(other.bindingIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              targetId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              funcId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              int v = input.readInt32();
              ensureBindingIdsIsMutable();
              bindingIds_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureBindingIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                bindingIds_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int targetId_ ;
    /**
     * <code>int32 target_id = 1;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public int getTargetId() {
      return targetId_;
    }
    /**
     * <code>int32 target_id = 1;</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(int value) {

      targetId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 target_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      targetId_ = 0;
      onChanged();
      return this;
    }

    private int funcId_ ;
    /**
     * <code>int32 func_id = 2;</code>
     * @return The funcId.
     */
    @java.lang.Override
    public int getFuncId() {
      return funcId_;
    }
    /**
     * <code>int32 func_id = 2;</code>
     * @param value The funcId to set.
     * @return This builder for chaining.
     */
    public Builder setFuncId(int value) {

      funcId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 func_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFuncId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      funcId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList bindingIds_ = emptyIntList();
    private void ensureBindingIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        bindingIds_ = mutableCopy(bindingIds_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @return A list containing the bindingIds.
     */
    public java.util.List<java.lang.Integer>
        getBindingIdsList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(bindingIds_) : bindingIds_;
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @return The count of bindingIds.
     */
    public int getBindingIdsCount() {
      return bindingIds_.size();
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The bindingIds at the given index.
     */
    public int getBindingIds(int index) {
      return bindingIds_.getInt(index);
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The bindingIds to set.
     * @return This builder for chaining.
     */
    public Builder setBindingIds(
        int index, int value) {

      ensureBindingIdsIsMutable();
      bindingIds_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @param value The bindingIds to add.
     * @return This builder for chaining.
     */
    public Builder addBindingIds(int value) {

      ensureBindingIdsIsMutable();
      bindingIds_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @param values The bindingIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllBindingIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureBindingIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, bindingIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 binding_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBindingIds() {
      bindingIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.sast.codegraph.repopb.MakeClosure)
  }

  // @@protoc_insertion_point(class_scope:security.sast.codegraph.repopb.MakeClosure)
  private static final MakeClosure DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MakeClosure();
  }

  public static MakeClosure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MakeClosure>
      PARSER = new com.google.protobuf.AbstractParser<MakeClosure>() {
    @java.lang.Override
    public MakeClosure parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MakeClosure> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MakeClosure> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MakeClosure getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

