// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

public interface StatementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.Statement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.security.sast.codegraph.repopb.CommonFlow common_flow = 1;</code>
   * @return Whether the commonFlow field is set.
   */
  boolean hasCommonFlow();
  /**
   * <code>.security.sast.codegraph.repopb.CommonFlow common_flow = 1;</code>
   * @return The commonFlow.
   */
  CommonFlow getCommonFlow();
  /**
   * <code>.security.sast.codegraph.repopb.CommonFlow common_flow = 1;</code>
   */
  CommonFlowOrBuilder getCommonFlowOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.Call call = 2;</code>
   * @return Whether the call field is set.
   */
  boolean hasCall();
  /**
   * <code>.security.sast.codegraph.repopb.Call call = 2;</code>
   * @return The call.
   */
  Call getCall();
  /**
   * <code>.security.sast.codegraph.repopb.Call call = 2;</code>
   */
  CallOrBuilder getCallOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.SetField set_field = 3;</code>
   * @return Whether the setField field is set.
   */
  boolean hasSetField();
  /**
   * <code>.security.sast.codegraph.repopb.SetField set_field = 3;</code>
   * @return The setField.
   */
  SetField getSetField();
  /**
   * <code>.security.sast.codegraph.repopb.SetField set_field = 3;</code>
   */
  SetFieldOrBuilder getSetFieldOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.StorePtr store_ptr = 4;</code>
   * @return Whether the storePtr field is set.
   */
  boolean hasStorePtr();
  /**
   * <code>.security.sast.codegraph.repopb.StorePtr store_ptr = 4;</code>
   * @return The storePtr.
   */
  StorePtr getStorePtr();
  /**
   * <code>.security.sast.codegraph.repopb.StorePtr store_ptr = 4;</code>
   */
  StorePtrOrBuilder getStorePtrOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.GetFieldAddr get_field_addr = 5;</code>
   * @return Whether the getFieldAddr field is set.
   */
  boolean hasGetFieldAddr();
  /**
   * <code>.security.sast.codegraph.repopb.GetFieldAddr get_field_addr = 5;</code>
   * @return The getFieldAddr.
   */
  GetFieldAddr getGetFieldAddr();
  /**
   * <code>.security.sast.codegraph.repopb.GetFieldAddr get_field_addr = 5;</code>
   */
  GetFieldAddrOrBuilder getGetFieldAddrOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.GetField get_field = 6;</code>
   * @return Whether the getField field is set.
   */
  boolean hasGetField();
  /**
   * <code>.security.sast.codegraph.repopb.GetField get_field = 6;</code>
   * @return The getField.
   */
  GetField getGetField();
  /**
   * <code>.security.sast.codegraph.repopb.GetField get_field = 6;</code>
   */
  GetFieldOrBuilder getGetFieldOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.LoadPtr load_ptr = 7;</code>
   * @return Whether the loadPtr field is set.
   */
  boolean hasLoadPtr();
  /**
   * <code>.security.sast.codegraph.repopb.LoadPtr load_ptr = 7;</code>
   * @return The loadPtr.
   */
  LoadPtr getLoadPtr();
  /**
   * <code>.security.sast.codegraph.repopb.LoadPtr load_ptr = 7;</code>
   */
  LoadPtrOrBuilder getLoadPtrOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.MakeClosure make_closure = 8;</code>
   * @return Whether the makeClosure field is set.
   */
  boolean hasMakeClosure();
  /**
   * <code>.security.sast.codegraph.repopb.MakeClosure make_closure = 8;</code>
   * @return The makeClosure.
   */
  MakeClosure getMakeClosure();
  /**
   * <code>.security.sast.codegraph.repopb.MakeClosure make_closure = 8;</code>
   */
  MakeClosureOrBuilder getMakeClosureOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.Phi phi = 9;</code>
   * @return Whether the phi field is set.
   */
  boolean hasPhi();
  /**
   * <code>.security.sast.codegraph.repopb.Phi phi = 9;</code>
   * @return The phi.
   */
  Phi getPhi();
  /**
   * <code>.security.sast.codegraph.repopb.Phi phi = 9;</code>
   */
  PhiOrBuilder getPhiOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.Operation operation = 10;</code>
   * @return Whether the operation field is set.
   */
  boolean hasOperation();
  /**
   * <code>.security.sast.codegraph.repopb.Operation operation = 10;</code>
   * @return The operation.
   */
  Operation getOperation();
  /**
   * <code>.security.sast.codegraph.repopb.Operation operation = 10;</code>
   */
  OperationOrBuilder getOperationOrBuilder();

  /**
   * <code>.security.sast.codegraph.repopb.Pos pos = 101;</code>
   * @return Whether the pos field is set.
   */
  boolean hasPos();
  /**
   * <code>.security.sast.codegraph.repopb.Pos pos = 101;</code>
   * @return The pos.
   */
  Pos getPos();
  /**
   * <code>.security.sast.codegraph.repopb.Pos pos = 101;</code>
   */
  PosOrBuilder getPosOrBuilder();

  Statement.KindCase getKindCase();
}
