// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

public interface StorePtrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.sast.codegraph.repopb.StorePtr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ptr_id = 1;</code>
   * @return The ptrId.
   */
  int getPtrId();

  /**
   * <code>int32 value_id = 2;</code>
   * @return The valueId.
   */
  int getValueId();
}
