// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stmt.proto

package org.example.core.hook.bytedance.proto;

/**
 * <pre>
 * StorePtr *ptr = value
 * </pre>
 *
 * Protobuf type {@code security.sast.codegraph.repopb.StorePtr}
 */
public final class StorePtr extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.sast.codegraph.repopb.StorePtr)
    StorePtrOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StorePtr.newBuilder() to construct.
  private StorePtr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StorePtr() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StorePtr();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_StorePtr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_StorePtr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StorePtr.class, StorePtr.Builder.class);
  }

  public static final int PTR_ID_FIELD_NUMBER = 1;
  private int ptrId_ = 0;
  /**
   * <code>int32 ptr_id = 1;</code>
   * @return The ptrId.
   */
  @java.lang.Override
  public int getPtrId() {
    return ptrId_;
  }

  public static final int VALUE_ID_FIELD_NUMBER = 2;
  private int valueId_ = 0;
  /**
   * <code>int32 value_id = 2;</code>
   * @return The valueId.
   */
  @java.lang.Override
  public int getValueId() {
    return valueId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ptrId_ != 0) {
      output.writeInt32(1, ptrId_);
    }
    if (valueId_ != 0) {
      output.writeInt32(2, valueId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ptrId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ptrId_);
    }
    if (valueId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, valueId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StorePtr)) {
      return super.equals(obj);
    }
    StorePtr other = (StorePtr) obj;

    if (getPtrId()
        != other.getPtrId()) return false;
    if (getValueId()
        != other.getValueId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PTR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPtrId();
    hash = (37 * hash) + VALUE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getValueId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StorePtr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StorePtr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StorePtr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StorePtr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StorePtr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StorePtr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StorePtr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StorePtr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static StorePtr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static StorePtr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StorePtr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StorePtr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StorePtr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * StorePtr *ptr = value
   * </pre>
   *
   * Protobuf type {@code security.sast.codegraph.repopb.StorePtr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.sast.codegraph.repopb.StorePtr)
          StorePtrOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_StorePtr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_StorePtr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StorePtr.class, StorePtr.Builder.class);
    }

    // Construct using org.example.core.processor.bytedance.proto.StorePtr.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ptrId_ = 0;
      valueId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CodeGraphStatement.internal_static_security_sast_codegraph_repopb_StorePtr_descriptor;
    }

    @java.lang.Override
    public StorePtr getDefaultInstanceForType() {
      return StorePtr.getDefaultInstance();
    }

    @java.lang.Override
    public StorePtr build() {
      StorePtr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public StorePtr buildPartial() {
      StorePtr result = new StorePtr(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(StorePtr result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ptrId_ = ptrId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.valueId_ = valueId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StorePtr) {
        return mergeFrom((StorePtr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StorePtr other) {
      if (other == StorePtr.getDefaultInstance()) return this;
      if (other.getPtrId() != 0) {
        setPtrId(other.getPtrId());
      }
      if (other.getValueId() != 0) {
        setValueId(other.getValueId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ptrId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              valueId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int ptrId_ ;
    /**
     * <code>int32 ptr_id = 1;</code>
     * @return The ptrId.
     */
    @java.lang.Override
    public int getPtrId() {
      return ptrId_;
    }
    /**
     * <code>int32 ptr_id = 1;</code>
     * @param value The ptrId to set.
     * @return This builder for chaining.
     */
    public Builder setPtrId(int value) {

      ptrId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ptr_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPtrId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ptrId_ = 0;
      onChanged();
      return this;
    }

    private int valueId_ ;
    /**
     * <code>int32 value_id = 2;</code>
     * @return The valueId.
     */
    @java.lang.Override
    public int getValueId() {
      return valueId_;
    }
    /**
     * <code>int32 value_id = 2;</code>
     * @param value The valueId to set.
     * @return This builder for chaining.
     */
    public Builder setValueId(int value) {

      valueId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 value_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValueId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      valueId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.sast.codegraph.repopb.StorePtr)
  }

  // @@protoc_insertion_point(class_scope:security.sast.codegraph.repopb.StorePtr)
  private static final StorePtr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StorePtr();
  }

  public static StorePtr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StorePtr>
      PARSER = new com.google.protobuf.AbstractParser<StorePtr>() {
    @java.lang.Override
    public StorePtr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StorePtr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StorePtr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public StorePtr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

